import { env } from 'cloudflare:workers';
import { NextResponse } from 'next/server';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { canReviewChange,resolveBootstrapRole,type ReviewerGrant,type ReviewableChange } from '@/lib/catalog-permissions';
import { canMaterializeCatalogField,validateMaterializableChange } from '@/lib/catalog-publication';
import { contributionTaxa } from '@/lib/catalog-taxonomy';
type Change=ReviewableChange & {status:string;reviewVersion:number;proposalKind:string;targetTaxonId:string|null};
async function grantsFor(id:string,email:string):Promise<ReviewerGrant[]>{const result=await env.DB!.prepare('SELECT user_id AS userId,role,region,taxonomic_group AS taxonomicGroup,active FROM catalog_role_grants WHERE user_id=? AND active=1').bind(id).all<ReviewerGrant>();const grants=result.results.map(row=>({...row,active:Boolean(row.active)}));const role=resolveBootstrapRole(email,(env as unknown as {CATALOG_CURATOR_EMAILS?:string}).CATALOG_CURATOR_EMAILS);if(role)grants.push({userId:id,role,region:null,taxonomicGroup:null,active:true});return grants;}
export async function GET(){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Registrazione richiesta.'},{status:401});if(!env.DB)return NextResponse.json({error:'Archivio non disponibile.'},{status:503});const grants=await grantsFor(user.userId,user.email);if(!grants.length)return NextResponse.json({error:'Non hai un incarico di revisione attivo.'},{status:403});const rows=await env.DB.prepare("SELECT cs.id,cs.author_id AS authorId,u.display_name AS authorName,cs.target_taxon_id AS targetTaxonId,cs.proposal_kind AS proposalKind,cs.status,cs.criticality,cs.region_scope AS regionScope,cs.taxonomic_scope AS taxonomicScope,cs.rationale,fc.field_path AS fieldPath,fc.proposed_value_json AS proposedValueJson,fc.source_citation AS sourceCitation,cs.created_at AS createdAt,(SELECT COUNT(*) FROM catalog_review_decisions rd WHERE rd.change_set_id=cs.id) AS reviewVersion FROM catalog_change_sets cs JOIN users u ON u.id=cs.author_id JOIN catalog_field_changes fc ON fc.change_set_id=cs.id WHERE cs.status IN('submitted','inReview','changesRequested','approved') ORDER BY cs.created_at ASC").all<Change>();return NextResponse.json({role:grants.some(g=>g.role==='scientificCurator')?'scientificCurator':'mycologist',changes:rows.results.filter(row=>canReviewChange(grants,row))},{headers:{'Cache-Control':'private, no-store'}});}
export async function POST(request:Request){
 const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Registrazione richiesta.'},{status:401});if(!env.DB)return NextResponse.json({error:'Archivio non disponibile.'},{status:503});
 let raw:unknown;try{raw=await request.json();}catch{return NextResponse.json({error:'Decisione non valida.'},{status:400});}
 if(!raw||typeof raw!=='object'||Array.isArray(raw))return NextResponse.json({error:'Decisione non valida.'},{status:400});
 const input=raw as {changeSetId?:string;decision?:string;notes?:string;expectedReviewVersion?:number};
 if(typeof input.changeSetId!=='string'||!['approve','reject','requestChanges'].includes(input.decision??'')||(input.notes!==undefined&&typeof input.notes!=='string')||(input.expectedReviewVersion!==undefined&&(!Number.isInteger(input.expectedReviewVersion)||input.expectedReviewVersion<0)))return NextResponse.json({error:'Decisione non valida.'},{status:400});
 const change=await env.DB.prepare("SELECT cs.id,cs.author_id AS authorId,cs.criticality,cs.region_scope AS regionScope,cs.taxonomic_scope AS taxonomicScope,cs.proposal_kind AS proposalKind,cs.target_taxon_id AS targetTaxonId,cs.status,(SELECT COUNT(*) FROM catalog_review_decisions rd WHERE rd.change_set_id=cs.id) AS reviewVersion FROM catalog_change_sets cs WHERE cs.id=? AND cs.status IN('submitted','inReview')").bind(input.changeSetId).first<Change>();if(!change)return NextResponse.json({error:'Proposta non disponibile per la revisione.'},{status:409});
 const grants=await grantsFor(user.userId,user.email);if(!canReviewChange(grants,change))return NextResponse.json({error:'Proposta fuori dal tuo ambito di competenza o di tua autoria.'},{status:403});
 if(input.expectedReviewVersion!==undefined&&input.expectedReviewVersion!==change.reviewVersion)return NextResponse.json({error:'Revisione aggiornata: ricarica la proposta.'},{status:409});
 const prior=await env.DB.prepare("SELECT reviewer_id AS reviewerId FROM catalog_review_decisions WHERE change_set_id=? AND stage='mycologist' AND decision='approve' ORDER BY created_at,id LIMIT 1").bind(change.id).first<{reviewerId:string}>();
 const curator=grants.some(g=>g.active&&g.role==='scientificCurator');
 if(change.criticality==='critical'&&prior&&input.decision==='approve'&&(!curator||prior.reviewerId===user.userId))return NextResponse.json({error:'Serve un curatore scientifico diverso dal primo revisore.'},{status:403});
 const stage=change.criticality==='critical'&&prior&&input.decision==='approve'?'scientific':'mycologist';
 const fields=await env.DB.prepare('SELECT field_path AS fieldPath,proposed_value_json AS proposedValueJson FROM catalog_field_changes WHERE change_set_id=?').bind(change.id).all<{fieldPath:string;proposedValueJson:string}>();
 const errors=fields.results.filter(field=>canMaterializeCatalogField(field.fieldPath)).map(field=>validateMaterializableChange({...field,proposalKind:change.proposalKind,targetTaxonId:change.targetTaxonId},contributionTaxa)).filter(Boolean);
 if(input.decision==='approve'&&errors.length)return NextResponse.json({error:errors.join(' ')},{status:400});
 const materializable=fields.results.length>0&&fields.results.every(field=>canMaterializeCatalogField(field.fieldPath));
 const status=input.decision==='reject'?'rejected':input.decision==='requestChanges'?'changesRequested':change.criticality==='ordinary'||stage==='scientific'?(materializable?'published':'approved'):'inReview';
 const decisionId=crypto.randomUUID(),releaseId=status==='published'?crypto.randomUUID():null,now=new Date().toISOString();
 try{const result=await env.DB.batch([
 env.DB.prepare("INSERT INTO users(id,email,display_name,role) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,display_name=excluded.display_name,updated_at=CURRENT_TIMESTAMP").bind(user.userId,user.email,user.displayName,curator?'scientificCurator':'mycologist'),
 env.DB.prepare("INSERT INTO catalog_review_decisions(id,change_set_id,reviewer_id,stage,decision,notes) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM catalog_change_sets cs WHERE cs.id=? AND cs.status=? AND cs.author_id<>? AND (SELECT COUNT(*) FROM catalog_review_decisions rd WHERE rd.change_set_id=cs.id)=?) AND NOT EXISTS(SELECT 1 FROM catalog_review_decisions WHERE change_set_id=? AND reviewer_id=?) AND (?<>'scientific' OR EXISTS(SELECT 1 FROM catalog_review_decisions WHERE change_set_id=? AND stage='mycologist' AND decision='approve' AND reviewer_id=? AND reviewer_id<>?))").bind(decisionId,change.id,user.userId,stage,input.decision,input.notes?.trim()??'',change.id,change.status,user.userId,change.reviewVersion,change.id,user.userId,stage,change.id,prior?.reviewerId??'',user.userId),
 env.DB.prepare('UPDATE catalog_change_sets SET status=?,published_release_id=?,updated_at=? WHERE id=? AND EXISTS(SELECT 1 FROM catalog_review_decisions WHERE id=?)').bind(status,releaseId,now,change.id,decisionId),
 ...(releaseId?[env.DB.prepare("INSERT INTO catalog_releases(id,version,published_by,published_at,source_report_json) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM catalog_change_sets cs WHERE cs.id=? AND cs.status='published' AND cs.published_release_id=?) AND EXISTS(SELECT 1 FROM catalog_review_decisions WHERE id=?)").bind(releaseId,'catalog-'+now.replace(/\D/g,'')+'-'+releaseId.slice(0,8),user.userId,now,JSON.stringify({changeSetId:change.id,decisionId}),change.id,releaseId,decisionId)]:[])
 ]);if(!result[1].meta.changes)return NextResponse.json({error:'Decisione già registrata o revisione aggiornata. Ricarica.'},{status:409});return NextResponse.json({id:change.id,status,stage,reviewVersion:change.reviewVersion+1});}catch(error){console.error('catalog_review_failed',error);return NextResponse.json({error:'Revisione non salvata. Riprova.'},{status:500});}
}
