import React,{useMemo,useState} from 'react';
import {FlatList,Linking,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {WebView} from 'react-native-webview';
export type Area={id:string;name:string;region:string;center:[number,number];habitat:string[];evidenceSources?:{label:string;url:string}[]};
function mapHtml(areas:Area[]){const data=JSON.stringify(areas).replace(/</g,'\\u003c');return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#map{height:100%;margin:0}</style></head><body><div id="map"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>function post(x){window.ReactNativeWebView.postMessage(JSON.stringify(x))}try{const areas=${data};const m=L.map('map').setView([42.4,12.5],5);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:16,attribution:'© OpenStreetMap contributors'}).addTo(m).on('tileerror',()=>post({error:true}));areas.forEach(a=>{const label=document.createElement('span');label.textContent=a.name+' · '+a.region;L.circleMarker(a.center,{radius:8,color:'#174f2b'}).addTo(m).bindTooltip(label).on('click',()=>post({id:a.id}));});post({ready:true});}catch(e){post({error:true});}</script></body></html>`;}
export default function Areas({areas}:{areas:Area[]}){
 const [query,setQuery]=useState(''),[region,setRegion]=useState('Tutte'),[map,setMap]=useState(false),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const norm=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const visible=useMemo(()=>areas.filter(a=>(region==='Tutte'||a.region===region)&&norm([a.name,a.region,...a.habitat].join(' ')).includes(norm(query))),[areas,region,query]);
 const regions=['Tutte',...new Set(areas.map(a=>a.region).sort())];
 const current=areas.find(a=>a.id===selected),html=useMemo(()=>mapHtml(visible),[visible]);
 async function open(url:string){if(!/^https:\/\//i.test(url))return;try{await Linking.openURL(url);}catch{setError('Collegamento non disponibile. Controlla la connessione.');}}
 const button=(label:string,onPress:()=>void)=><Pressable accessibilityRole="button" style={s.button} onPress={onPress}><Text style={s.green}>{label}</Text></Pressable>;
 return <View style={s.screen}><Text style={s.title}>Aree e habitat</Text><Text style={s.small}>{areas.length} macroaree in 20 regioni. Centri territoriali rappresentativi: non sono fungaie o percorsi di accesso verificati.</Text><TextInput accessibilityLabel="Cerca area o habitat" placeholder="Area, regione o habitat" value={query} onChangeText={setQuery} style={s.input}/><ScrollView horizontal style={s.regions} contentContainerStyle={s.row}>{regions.map(r=><Pressable key={r} accessibilityRole="button" accessibilityState={{selected:region===r}} onPress={()=>setRegion(r)} style={[s.button,region===r&&s.active]}><Text style={region===r?s.white:s.green}>{r}</Text></Pressable>)}</ScrollView><View style={s.row}>{button('Monte Amiata',()=>{setQuery('Amiata');setRegion('Tutte');})}{button(map?'Elenco offline':'Mappa online',()=>setMap(!map))}</View>{map&&<View style={s.map}><WebView key={retry} source={{html}} originWhitelist={['*']} onError={()=>setError('Mappa online non disponibile: consulta l’elenco offline.')} onMessage={e=>{try{const message=JSON.parse(e.nativeEvent.data);if(message.error)setError('Cartografia non disponibile: l’elenco resta consultabile.');if(typeof message.id==='string'&&visible.some(a=>a.id===message.id))setSelected(message.id);}catch{}}}/></View>}{!!error&&<View><Text accessibilityRole="alert" style={s.small}>{error}</Text>{button('Riprova mappa',()=>{setError('');setRetry(retry+1);})}</View>}{current&&<ScrollView style={s.detail} contentContainerStyle={s.card}><Text style={s.name}>{current.name}</Text><Text style={s.small}>{current.habitat.join(' · ')}</Text>{button('Apri centro macroarea nelle mappe',()=>void open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(current.center.join(','))))}{current.evidenceSources?.map(source=><Pressable key={source.url} accessibilityRole="link" style={s.button} onPress={()=>void open(source.url)}><Text style={s.green}>{source.label}</Text></Pressable>)}{button('Chiudi dettaglio',()=>setSelected(null))}</ScrollView>}<Text style={s.small}>{visible.length} aree corrispondenti</Text><FlatList data={visible} keyExtractor={a=>a.id} style={s.list} contentContainerStyle={{paddingBottom:24}} ListEmptyComponent={<Text>Nessuna area corrisponde ai filtri.</Text>} renderItem={({item:a})=><Pressable accessibilityRole="button" accessibilityLabel={'Consulta '+a.name} onPress={()=>setSelected(a.id)} style={s.card}><Text style={s.name}>{a.name}</Text><Text style={s.small}>{a.region} · {a.habitat.join(' · ')}</Text></Pressable>}/></View>;
}
const s=StyleSheet.create({screen:{flex:1,padding:16,gap:10},title:{fontSize:26,fontWeight:'800',color:'#174f2b'},small:{fontSize:14,lineHeight:21,color:'#435c49'},input:{minHeight:48,padding:12,borderWidth:1,borderColor:'#708576',borderRadius:12,backgroundColor:'white',fontSize:16},regions:{maxHeight:60,flexGrow:0},row:{flexDirection:'row',gap:8},button:{minHeight:48,padding:12,borderWidth:1,borderColor:'#b9cbb8',borderRadius:12,backgroundColor:'white',justifyContent:'center'},active:{backgroundColor:'#174f2b'},green:{color:'#174f2b',fontWeight:'700'},white:{color:'white',fontWeight:'700'},map:{height:220},detail:{maxHeight:230},list:{flex:1,minHeight:80},card:{padding:14,gap:8,backgroundColor:'white',borderWidth:1,borderColor:'#d5dfd3',borderRadius:14,marginBottom:10},name:{fontSize:17,fontWeight:'800',color:'#14261a'}});
