import React,{useState} from 'react';
import {Linking,Pressable,ScrollView,StyleSheet,Text} from 'react-native';
const origin='https://fungo-italia-beta.gianpaolo-franceschi.chatgpt.site';
export default function Community(){
 const [error,setError]=useState('');
 async function openGitHub(){try{setError('');await Linking.openURL('https://github.com/gianpaolobol/fungo-italia/issues/new?template=scientific-contribution.yml');}catch{setError('Apertura non riuscita. Verifica la connessione e riprova.');}}
 async function open(path:string){try{setError('');await Linking.openURL(origin+path);}catch{setError('Apertura non riuscita. Controlla la connessione e riprova.');}}
 return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>Contributi scientifici</Text><Text style={s.text}>Aiuta a migliorare l’atlante con una correzione documentata: indica il fungo, la modifica e una fonte verificabile.</Text><Pressable accessibilityRole="link" style={s.button} onPress={()=>void openGitHub()}><Text style={s.label}>Proponi una correzione scientifica su GitHub</Text></Pressable><Text style={s.text}>La proposta sarà pubblica e richiede un account GitHub. Non includere dati personali o coordinate precise; condividi solo foto pubblicabili. Sarà verificata prima di aggiornare l’atlante.</Text><Text style={s.text}>Servizio storico e account esistenti</Text><Pressable accessibilityRole="link" style={s.button} onPress={()=>void open('/catalog/proposals/new')}><Text style={s.label}>Apri una proposta documentata</Text></Pressable><Pressable accessibilityRole="link" style={s.button} onPress={()=>void open('/observations/new')}><Text style={s.label}>Invia un’osservazione con fotografie</Text></Pressable><Pressable accessibilityRole="link" style={s.button} onPress={()=>void open('/admin/catalog')}><Text style={s.label}>Apri gestione catalogo per curatori</Text></Pressable>{!!error&&<Text accessibilityRole="alert">{error}</Text>}</ScrollView>;
}
const s=StyleSheet.create({page:{padding:20,gap:16},title:{fontSize:26,fontWeight:'800',color:'#174f2b'},text:{fontSize:16,lineHeight:24,color:'#243f2c'},button:{minHeight:52,padding:16,backgroundColor:'#174f2b',borderRadius:12},label:{color:'white',fontWeight:'700',fontSize:16}});
