import React,{useState} from 'react';
import {Linking,Pressable,ScrollView,StyleSheet,Text} from 'react-native';
const origin='https://fungo-italia-beta.gianpaolo-franceschi.chatgpt.site';
export default function Community(){
 const [error,setError]=useState('');
 async function open(path:string){try{setError('');await Linking.openURL(origin+path);}catch{setError('Apertura non riuscita. Controlla la connessione e riprova.');}}
 return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>Contributi scientifici</Text><Text style={s.text}>Le bozze offline restano su questo dispositivo. Per inviare una proposta documentata usa il servizio web esistente con il tuo account; si aprirà il browser del telefono.</Text><Pressable accessibilityRole="link" style={s.button} onPress={()=>void open('/catalog/proposals/new')}><Text style={s.label}>Apri una proposta documentata</Text></Pressable><Pressable accessibilityRole="link" style={s.button} onPress={()=>void open('/observations/new')}><Text style={s.label}>Invia un’osservazione con fotografie</Text></Pressable><Pressable accessibilityRole="link" style={s.button} onPress={()=>void open('/admin/catalog')}><Text style={s.label}>Apri gestione catalogo per curatori</Text></Pressable><Text style={s.text}>Il ruolo e i permessi sono verificati dal servizio web. L’app non attribuisce ruoli locali né invia credenziali o coordinate automaticamente.</Text>{!!error&&<Text accessibilityRole="alert">{error}</Text>}<Text style={s.text}>La baseline didattica inclusa ha audit interno e revisione indipendente pendente. Le fonti puntuali sono riportate in ogni scheda; il nome di una pubblicazione non garantisce che sostenga tutti i caratteri mostrati.</Text></ScrollView>;
}
const s=StyleSheet.create({page:{padding:20,gap:16},title:{fontSize:26,fontWeight:'800',color:'#174f2b'},text:{fontSize:16,lineHeight:24,color:'#243f2c'},button:{minHeight:52,padding:16,backgroundColor:'#174f2b',borderRadius:12},label:{color:'white',fontWeight:'700',fontSize:16}});
