import React,{useEffect,useRef,useState} from 'react';
import {Alert,Button,ScrollView,Share,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
type Draft={id:string;date:string;taxon:string;habitat:string;characters:string;evidence:string;sources:string;notes:string;latitude:string;longitude:string;updatedAt:string};
let pendingWrites:Promise<void>=Promise.resolve();
const key='fungo-italia:observation-drafts:v1';
const fields=['date','taxon','habitat','characters','evidence','sources','notes','latitude','longitude'] as const;
const labels={date:'Data (AAAA-MM-GG)',taxon:'Ipotesi tassonomica',habitat:'Habitat e substrato',characters:'Caratteri osservati',evidence:'Evidenze, foto di riferimento e limiti',sources:'Fonti: autore, titolo, pagina, DOI o URL',notes:'Note',latitude:'Latitudine facoltativa',longitude:'Longitudine facoltativa'};
const fresh=():Draft=>({id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),date:new Date().toISOString().slice(0,10),taxon:'',habitat:'',characters:'',evidence:'',sources:'',notes:'',latitude:'',longitude:'',updatedAt:new Date().toISOString()});
export default function Drafts(){
 const [rows,setRows]=useState<Draft[]>([]),[selected,setSelected]=useState<string|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[retry,setRetry]=useState(0);
 const latest=useRef<Draft[]>([]),revision=useRef(0),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{let active=true;pendingWrites.catch(()=>{}).then(()=>AsyncStorage.getItem(key)).then(raw=>{if(!active)return;const value=raw?JSON.parse(raw):{version:1,drafts:[]};if(value.version!==1||!Array.isArray(value.drafts)||!value.drafts.every((d:Draft)=>d&&typeof d.id==='string'&&typeof d.updatedAt==='string'&&fields.every(k=>typeof d[k]==='string'))||new Set(value.drafts.map((d:Draft)=>d.id)).size!==value.drafts.length)throw Error('Formato');latest.current=value.drafts;setRows(value.drafts);setSelected(value.drafts[0]?.id??null);setError('');setReady(true);}).catch(()=>{if(active)setError('Bozze non leggibili. I dati esistenti non sono stati sovrascritti.');});return()=>{active=false;};},[retry]);
 function persist(next:Draft[]){const current=++revision.current;setStatus('Salvataggio…');const payload=JSON.stringify({version:1,drafts:next});pendingWrites=pendingWrites.catch(()=>{}).then(()=>AsyncStorage.setItem(key,payload)).then(()=>{if(alive.current&&revision.current===current)setStatus('Salvato sul dispositivo.');}).catch(()=>{if(alive.current&&revision.current===current)setStatus('Salvataggio non riuscito: riprova prima di chiudere.');});}
 function replace(next:Draft[]){latest.current=next;setRows(next);persist(next);}
 const draft=rows.find(d=>d.id===selected);
 function update(field:typeof fields[number],value:string){if(draft)replace(latest.current.map(d=>d.id===draft.id?{...d,[field]:value,updatedAt:new Date().toISOString()}:d));}
 function add(){const d=fresh();replace([d,...latest.current]);setSelected(d.id);}
 function remove(){if(!draft)return;const id=draft.id;Alert.alert('Eliminare la bozza?','La rimozione riguarda questo dispositivo.',[{text:'Annulla',style:'cancel'},{text:'Elimina',style:'destructive',onPress:()=>{const next=latest.current.filter(d=>d.id!==id);replace(next);setSelected(next[0]?.id??null);}}]);}
 async function share(includeCoordinates:boolean){if(!draft)return;const parsed=new Date(draft.date+'T12:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(draft.date)||!Number.isFinite(parsed.getTime())||parsed.toISOString().slice(0,10)!==draft.date||draft.date>new Date().toISOString().slice(0,10)){Alert.alert('Data non valida','Usa una data reale nel formato AAAA-MM-GG, non futura.');return;}const hasLat=!!draft.latitude.trim(),hasLng=!!draft.longitude.trim(),lat=Number(draft.latitude.replace(',','.')),lng=Number(draft.longitude.replace(',','.'));if(hasLat!==hasLng||(hasLat&&(!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180))){Alert.alert('Coordinate non valide','Inserisci entrambe le coordinate oppure lasciale vuote.');return;}const {latitude,longitude,...content}=draft;const payload={format:'fungo-italia-observation-draft',version:1,status:'local-unreviewed-draft',notice:'Ipotesi non verificata. Nessuna validazione scientifica. Non autorizza il consumo.',observation:content,...(includeCoordinates&&hasLat?{privateCoordinates:{latitude:lat,longitude:lng}}:{})};try{await Share.share({title:'Bozza Fungo Italia',message:JSON.stringify(payload,null,2)});}catch{Alert.alert('Esportazione non riuscita','La bozza resta sul dispositivo.');}}
 function exportDraft(){if(!draft)return;if(draft.latitude.trim()||draft.longitude.trim())Alert.alert('Esporta la bozza','Le coordinate precise sono escluse per impostazione predefinita.',[{text:'Annulla',style:'cancel'},{text:'Senza coordinate',onPress:()=>void share(false)},{text:'Includi coordinate private',onPress:()=>void share(true)}]);else void share(false);}
 if(!ready)return <View style={s.page}><Text style={s.title}>Osservazioni offline</Text><Text accessibilityRole="alert">{error||'Caricamento…'}</Text>{!!error&&<Button title="Riprova lettura" onPress={()=>setRetry(retry+1)}/>}</View>;
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Text style={s.title}>Osservazioni offline</Text><Text style={s.text}>Annota ritrovamenti e caratteri osservati. Le note restano su questo dispositivo: esportale per conservarle.</Text><Button title="Nuova bozza" onPress={add}/>{rows.map(d=><View key={d.id} style={{marginVertical:4}}><Button title={(d.id===selected?'✓ ':'')+(d.taxon||'Taxon non determinato')+' · '+d.date} onPress={()=>setSelected(d.id)}/></View>)}{draft?<View>{fields.map(field=><View key={field} style={s.field}><Text style={s.label}>{labels[field]}</Text><TextInput accessibilityLabel={labels[field]} value={draft[field]} onChangeText={value=>update(field,value)} multiline={!['date','taxon','latitude','longitude'].includes(field)} keyboardType={['latitude','longitude'].includes(field)?'numbers-and-punctuation':'default'} style={s.input}/></View>)}<Text accessibilityLiveRegion="polite" style={s.text}>{status}</Text><View style={s.field}><Button title="Salva di nuovo" onPress={()=>persist(latest.current)}/></View><View style={s.field}><Button title="Esporta JSON" onPress={exportDraft}/></View><View style={s.field}><Button title="Elimina bozza" color="#a12f28" onPress={remove}/></View><Text style={s.text}>Per le fotografie, indica un riferimento nel campo Evidenze.</Text></View>:<Text style={s.text}>Nessuna bozza. Registra il prossimo ritrovamento.</Text>}</ScrollView>;
}
const s=StyleSheet.create({page:{padding:20,paddingBottom:48,backgroundColor:'#f4f7f2',flexGrow:1},title:{fontSize:28,fontWeight:'800',color:'#174f2b',marginBottom:12},text:{fontSize:16,lineHeight:24,marginVertical:12,color:'#243f2c'},field:{marginVertical:10},label:{fontSize:16,fontWeight:'700',marginBottom:6,color:'#174f2b'},input:{minHeight:48,borderWidth:1,borderColor:'#b6c8b7',backgroundColor:'#fff',borderRadius:10,padding:12,fontSize:16,color:'#14261a',textAlignVertical:'top'}});
