"use client";
import {useEffect,useState} from "react";
import type {AtlasTaxon} from "@/lib/domain";
import {buildOfflinePackage,cachePackageImages,prepareOfflineReader,readStoredPackage,readFavoriteIds,OFFLINE_PACKAGE_KEY,OFFLINE_FAVORITES_KEY,OFFLINE_RESUME_KEY,type OfflinePackage} from "@/lib/offline";
export function OfflineTaxonActions({taxonId}:{taxonId:string}){
 const[favorite,setFavorite]=useState(false);const[message,setMessage]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setFavorite(readFavoriteIds(localStorage.getItem(OFFLINE_FAVORITES_KEY)).includes(taxonId));localStorage.setItem(OFFLINE_RESUME_KEY,taxonId);}catch{setMessage("Il browser impedisce il salvataggio locale.");}},0);return()=>window.clearTimeout(timer);},[taxonId]);
 function toggle(){try{const ids=readFavoriteIds(localStorage.getItem(OFFLINE_FAVORITES_KEY));const next=ids.includes(taxonId)?ids.filter(id=>id!==taxonId):[...ids,taxonId];localStorage.setItem(OFFLINE_FAVORITES_KEY,JSON.stringify(next));setFavorite(next.includes(taxonId));setMessage(next.includes(taxonId)?"Preferito salvato su questo dispositivo. Per consultarlo senza rete scarica il pacchetto.":"Preferito rimosso.");window.dispatchEvent(new Event("fungo-offline-change"));}catch{setMessage("Impossibile salvare: spazio o permessi del browser insufficienti.");}}
 return <div className="my-3"><button type="button" aria-pressed={favorite} onClick={toggle} className="min-h-11 rounded-xl border border-green-800 px-4 py-2 font-bold text-green-900">{favorite?"Rimuovi dai preferiti":"Salva nei preferiti"}</button><p role="status" className="mt-1 text-sm">{message}</p></div>;
}
export function OfflineLibrary({taxa}:{taxa:readonly AtlasTaxon[]}){
 const[saved,setSaved]=useState<OfflinePackage|null>(null);const[favoriteCount,setFavoriteCount]=useState(0);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 useEffect(()=>{const refresh=()=>{setSaved(readStoredPackage());try{setFavoriteCount(readFavoriteIds(localStorage.getItem(OFFLINE_FAVORITES_KEY)).length);}catch{setFavoriteCount(0);}};const timer=window.setTimeout(refresh,0);window.addEventListener("fungo-offline-change",refresh);window.addEventListener("storage",refresh);return()=>{window.clearTimeout(timer);window.removeEventListener("fungo-offline-change",refresh);window.removeEventListener("storage",refresh);};},[]);
 async function download(){setBusy(true);setMessage("Download del lettore e delle schede…");try{if(!navigator.onLine)throw new Error("Collegati a Internet per scaricare o aggiornare il pacchetto.");if(!taxa.length)throw new Error("Apri la sezione Schede per scaricare il catalogo.");const registration=await prepareOfflineReader();const pack=buildOfflinePackage(taxa);const images=[...new Set(pack.cards.map(card=>card.image).filter((image):image is string=>Boolean(image)))];pack.cachedImages=await cachePackageImages(registration,images);localStorage.setItem(OFFLINE_PACKAGE_KEY,JSON.stringify(pack));setSaved(pack);setMessage("Pacchetto pronto: "+pack.cards.length+" schede e "+pack.cachedImages.length+" immagini locali. Apri il lettore e prova la modalità aereo.");}catch(error){setMessage(error instanceof Error?error.message:"Download non riuscito. Il pacchetto precedente è conservato.");}finally{setBusy(false);}}
 function remove(){try{localStorage.removeItem(OFFLINE_PACKAGE_KEY);setSaved(null);setMessage("Pacchetto rimosso. Preferiti e ultima scheda restano sul dispositivo.");}catch{setMessage("Il browser impedisce la rimozione del pacchetto.");}}
 return <section aria-label="Studio offline" className="my-4 rounded-2xl border border-green-200 bg-green-50 p-4 text-green-950"><h2 className="text-lg font-bold">Studio offline</h2><p className="mt-2 text-sm">Scarica esplicitamente le schede pubbliche, le note di sicurezza e le fonti. Preferiti e ripresa sono locali a questo browser, anche dopo la chiusura.</p><p className="mt-2 text-sm">Mappa, meteo aggiornato, invio di osservazioni e immagini esterne richiedono rete. Le immagini incluse sono soltanto quelle locali con provenienza e licenza disponibili; le immagini mancanti vengono segnalate.</p><p className="mt-2 text-sm">{favoriteCount} preferiti. {saved?saved.cards.length+" schede salvate · "+saved.version+" · "+new Date(saved.savedAt).toLocaleString("it-IT"):"Nessun pacchetto scaricato."}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy||!taxa.length} onClick={()=>void download()} className="min-h-11 rounded-xl bg-green-900 px-4 py-2 font-bold text-white disabled:opacity-50">{busy?"Download in corso…":saved?"Aggiorna pacchetto offline":"Scarica pacchetto offline"}</button><a href="/offline-reader.html" className="min-h-11 rounded-xl border border-green-800 px-4 py-2 font-bold">Apri lettore offline</a>{saved&&<button type="button" disabled={busy} onClick={remove} className="min-h-11 rounded-xl border px-4 py-2">Rimuovi pacchetto</button>}</div><p role="status" aria-live="polite" className="mt-2 text-sm">{message}</p><p className="mt-2 text-xs">Il browser può liberare lo spazio locale. Controlla il lettore prima di partire; non è un’autorizzazione al consumo. Un aggiornamento sostituisce il pacchetto solo al termine del download.</p></section>;
}
