import React,{useState} from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import bankData from '../src/data/exam-bank.json';
import {referenceImageAssets} from '../src/data/reference-image-assets';
import {selectCases,gradeAnswer,foodLabels} from '../web/public/exam-core';
type Case={id:string;name:string;acceptedNames:string[];category:string;detailKind:string|null;preparation:string[];syndrome:{label:string;latency?:string;severity?:string}|null;photos:{src:string;view:string}[]};
type Answer={name:string;category:string;detail:string};
const bank=bankData as unknown as Case[];
const labels=foodLabels;
export default function PhotoExam(){
 const [cases,setCases]=useState<Case[]>([]),[answers,setAnswers]=useState<Answer[]>([]),[index,setIndex]=useState(0),[answer,setAnswer]=useState<Answer>({name:'',category:'',detail:''}),[complete,setComplete]=useState(false);
 function start(){setCases(selectCases(bank));setAnswers([]);setIndex(0);setAnswer({name:'',category:'',detail:''});setComplete(false);}
 function next(){const updated=[...answers,answer];setAnswers(updated);if(index===14)setComplete(true);else{setIndex(index+1);setAnswer({name:'',category:'',detail:''});}}
 const current=cases[index];
 if(!current)return <View style={s.page}><Text style={s.title}>Esame fotografico</Text><Text style={s.text}>15 funghi da riconoscere: nome scientifico, commestibilità e spiegazione della preparazione oppure della tossicità. I nomi vengono mostrati soltanto alla fine.</Text><Text style={s.text}>È un esercizio didattico. Le fotografie non autorizzano l’identificazione per il consumo.</Text><Pressable accessibilityRole="button" onPress={start} style={s.button}><Text style={s.buttonText}>Inizia 15 casi</Text></Pressable></View>;
 if(complete)return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>Risultati dei 15 casi</Text><Text style={s.text}>Nome e categoria sono confrontati automaticamente. Le spiegazioni richiedono autovalutazione o revisione di un docente.</Text>{cases.map((c,i)=>{const a=answers[i],graded=gradeAnswer(c,a),nameCorrect=graded.name,categoryCorrect=graded.category,danger=graded.danger;return <View key={c.id} style={s.card}><Text style={s.heading}>{i+1}. {c.name}</Text><Text style={s.text}>Nome: {a.name||'Non risposto'} · {nameCorrect?'corretto':'da correggere'}</Text><Text style={s.text}>Categoria: {labels[a.category]||'Non risposto'} · {categoryCorrect?'corretta':'da correggere'}</Text><Text style={s.heading}>Giudizio: {labels[c.category]}</Text>{danger&&<Text style={s.danger}>Risposta alimentare pericolosa: rivedere categoria e condizioni.</Text>}{c.detailKind==='preparation'&&c.preparation.map((text,j)=><Text key={j} style={s.text}>• {text}</Text>)}{c.detailKind==='toxicology'&&c.syndrome&&<Text style={s.text}>{c.syndrome.label}{'\n'}{c.syndrome.latency}{'\n'}{c.syndrome.severity}</Text>}<Text style={s.text}>La tua spiegazione: {a.detail||'Non risposto'}</Text></View>;})}<Pressable accessibilityRole="button" onPress={start} style={s.button}><Text style={s.buttonText}>Nuova simulazione</Text></Pressable></ScrollView>;
 return <ScrollView key={current.id} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Text style={s.title}>Caso {index+1} / 15</Text><Text style={s.text}>Identifica il fungo dalle viste disponibili. La risposta sarà mostrata al termine.</Text>{current.photos.map((p,i)=>referenceImageAssets[p.src]&&<Image key={p.src} accessibilityLabel={'Vista fotografica '+(i+1)+' del fungo da identificare'} source={referenceImageAssets[p.src]} resizeMode="contain" style={s.photo}/>)}<Text style={s.heading}>Nome scientifico</Text><TextInput accessibilityLabel="Nome scientifico della risposta" style={s.input} autoCorrect={false} value={answer.name} onChangeText={name=>setAnswer({...answer,name})}/><Text style={s.heading}>Commestibilità</Text>{Object.entries(labels).map(([category,label])=><Pressable key={category} accessibilityRole="radio" accessibilityState={{selected:answer.category===category}} onPress={()=>setAnswer({...answer,category})} style={[s.option,answer.category===category&&s.selected]}><Text style={s.text}>{answer.category===category?'● ':'○ '}{label}</Text></Pressable>)}<Text style={s.heading}>Preparazione o tossicità</Text><Text style={s.text}>Se condizionata, indica trattamenti e precauzioni. Se tossica o mortale, descrivi sindrome, latenza e gravità.</Text><TextInput accessibilityLabel="Spiegazione di preparazione o tossicità" multiline style={[s.input,{minHeight:100}]} value={answer.detail} onChangeText={detail=>setAnswer({...answer,detail})}/><Pressable accessibilityRole="button" onPress={next} style={s.button}><Text style={s.buttonText}>{index===14?'Concludi e mostra risultati':'Salva risposta e prosegui'}</Text></Pressable></ScrollView>;
}
const s=StyleSheet.create({page:{padding:16,gap:12},title:{fontSize:22,fontWeight:'800',color:'#174f2b'},heading:{fontWeight:'700',fontSize:16,color:'#174f2b'},text:{fontSize:15,lineHeight:22,color:'#304b39'},card:{padding:14,gap:8,backgroundColor:'#fff',borderRadius:12},photo:{width:'100%',height:210,backgroundColor:'#e8eee5',borderRadius:12},input:{padding:12,borderWidth:1,borderColor:'#789180',borderRadius:10,backgroundColor:'#fff',fontSize:16},option:{padding:12,minHeight:46,borderWidth:1,borderColor:'#ccd8cb',borderRadius:10},selected:{backgroundColor:'#d8ebc2',borderColor:'#174f2b'},button:{padding:14,minHeight:48,backgroundColor:'#174f2b',borderRadius:12,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'700'},danger:{color:'#a32424',fontWeight:'700'}});
