import React,{useMemo,useRef,useState} from 'react';
import {Alert,FlatList,Linking,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
const ranks:Record<string,string>={species:'Specie',genus:'Genere',section:'Sezione',group:'Gruppo',speciesGroup:'Gruppo di specie',aggregate:'Aggregato',operationalGroup:'Gruppo operativo',family:'Famiglia',subgenus:'Sottogenere',subsection:'Sottosezione',subspecies:'Sottospecie',variety:'Varietà'};
export type StudyTaxon={id:string;scientificName:string;commonNames:string[];summary:string;characters:string[];differentiatingCharacter?:string;lookalikes:string[];habitat:string[];sources:{sourceId?:string;title:string;location?:string;url?:string|null;supportedClaim?:string;notes?:string|null}[];aliases?:string[];rank?:string;currentAcceptedNames?:string[];diagnosticStatus?:string;diagnosticNote?:string|null;kind?:string;relatedIds?:string[];currentGenera?:string[];deepMorphologyRequired?:boolean;authorship?:string|null;family?:string|null;division?:string;order?:string};
type Props={taxa:StudyTaxon[];favoriteIds:string[];onFavoriteIdsChange:(ids:string[])=>void;resumeId:string|null;onResumeChange:(id:string)=>void;catalogVersion:string};
const diagnosticLimits:Record<string,string>={field_high_confidence:'Caratteri di campo; determinazione da verificare',field_high_confidence_when_typical:'Condizione: esemplari tipici',field_high_confidence_when_host_known:'Ospite ed ecologia devono essere noti',field_high_confidence_when_young:'Condizione: esemplari giovani',field_high_confidence_at_source_rank:'Risoluzione limitata al rango didattico S1',field_confirmatory:'Conferma specialistica nei casi dubbi',defined_morphogroup_s1:'Morfogruppo didattico S1',defined_set_s1:'Insieme didattico definito S1',microscopy_required_for_fine_id:'Microscopia necessaria per la specie fine',dna_confirmatory:'Conferma molecolare per la risoluzione fine'};
const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('it').trim();
function Button({label,onPress,disabled=false,selected=false}:{label:string;onPress:()=>void;disabled?:boolean;selected?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled,selected}} disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled,selected&&s.selectedButton]}><Text style={s.buttonText}>{label}</Text></Pressable>;}
function SourceLink({url}:{url:string}){const [error,setError]=useState('');const safe=/^https:\/\//i.test(url);async function openSource(){if(!safe)return;setError('');try{await Linking.openURL(url);}catch{setError('Fonte non aperta. Verifica la connessione oppure copia il collegamento.');}}return <View style={{gap:6}}><Text selectable style={s.small}>{url}</Text>{safe&&<Pressable accessibilityRole="link" accessibilityLabel={'Apri fonte '+url} onPress={()=>void openSource()} style={s.button}><Text style={s.buttonText}>Apri fonte esterna</Text></Pressable>}{safe&&<Text style={s.small}>La fonte esterna richiede connessione.</Text>}{!!error&&<Text accessibilityRole="alert" style={s.notice}>{error}</Text>}</View>;}
function studyText(value:string){
 return value.replace(/ richiesto da S1/g,'').replace(/Nel defined set S1,/g,'In questo gruppo,').replace(/ectomicorrizico S1:/g,'ectomicorrizico:').replace(/Morfogruppo S1 dei/g,'Gruppo dei').replace(/; gruppo didattico S1\./g,'.').replace(/; profilo volutamente al rango Hydnum spp\.\/gruppo S1\./g,'.').replace(/S1 include A\. vidua; /g,'Il gruppo include A. vidua; ').replace(/Denominazione S1 mantenuta; /g,'');
}
function Content({taxon:t}:{taxon:StudyTaxon}){
 const sources=t.sources.filter(source=>!/^AUDIT-|^EDITORIAL-/.test(source.sourceId??'')&&!/^Scientific Baseline\b/.test(source.title));
 const summary=t.summary.startsWith('Unità didattica al rango ')||t.summary.startsWith('Obiettivo didattico di genere o gruppo.')?'':t.summary;
 const diagnostic=['field_high_confidence_when_typical','field_high_confidence_when_host_known','field_high_confidence_when_young','microscopy_required_for_fine_id','dna_confirmatory'].includes(t.diagnosticStatus??'')?diagnosticLimits[t.diagnosticStatus??'']:'';
 return <View style={s.content}><Text accessibilityRole="header" style={s.name}>{t.scientificName}</Text><Text style={s.small}>{ranks[t.rank??'']??t.rank??''}</Text>{!!t.commonNames.length&&<Text style={s.common}>{t.commonNames.join(' · ')}</Text>}{!!diagnostic&&<Text style={s.small}>{diagnostic}</Text>}{!!t.diagnosticNote&&<Text style={s.small}>{studyText(t.diagnosticNote)}</Text>}{!!t.currentAcceptedNames?.length&&t.rank!=='species'&&<Text style={s.small}>Nomi compresi: {t.currentAcceptedNames.join(' · ')}</Text>}{!!t.authorship&&<Text style={s.small}>Autore nomenclaturale: {t.authorship}</Text>}{!!t.family&&<Text style={s.small}>Famiglia: {t.family}</Text>}{!!summary&&<Text style={s.text}>{summary}</Text>}{!!t.characters.length?<><Text style={s.heading}>Caratteri di studio</Text>{t.characters.map((c,i)=><Text key={i} style={s.text}>{i+1}. {studyText(c)}</Text>)}</>:<Text style={s.text}>Per studiare i caratteri, apri le schede collegate.</Text>}{!!t.differentiatingCharacter&&<><Text style={s.heading}>Carattere differenziante (+1)</Text><Text style={s.text}>{studyText(t.differentiatingCharacter)}</Text></>}{!!t.lookalikes.length&&<><Text style={s.heading}>Specie simili</Text><Text style={s.text}>{t.lookalikes.join('\n')}</Text></>}{!!t.habitat.length&&<><Text style={s.heading}>Habitat</Text><Text style={s.text}>{t.habitat.join(' · ')}</Text></>}{!!sources.length&&<Text style={s.heading}>Fonti</Text>}{sources.map((source,i)=><View key={i} style={s.source}><Text selectable style={s.text}>{source.title}{source.location?' · '+source.location:''}</Text>{!!source.url&&<SourceLink url={source.url}/>}</View>)}</View>;
}

export default function Studio({taxa,favoriteIds,onFavoriteIdsChange,resumeId,onResumeChange,catalogVersion}:Props){
 const [filters,setFilters]=useState(false);
 const [layer,setLayer]=useState<'minimum'|'groups'|'all'>('minimum');
 const [query,setQuery]=useState(''),[only,setOnly]=useState(false),[feed,setFeed]=useState(false),[selected,setSelected]=useState<string|null>(null);
 const reading=useRef(false),resumeCallback=useRef(onResumeChange),lastRead=useRef<string|null>(resumeId);
 reading.current=feed;resumeCallback.current=onResumeChange;
 const readingConfig=useRef({minimumViewTime:400,viewAreaCoveragePercentThreshold:55}).current;
 const readingChanged=useRef(({viewableItems}:{viewableItems:Array<{item:StudyTaxon;isViewable:boolean}>})=>{if(!reading.current)return;const item=viewableItems.find(v=>v.isViewable)?.item;if(item&&lastRead.current!==item.id){lastRead.current=item.id;resumeCallback.current(item.id);}}).current;
 const visible=useMemo(()=>taxa.filter(t=>(layer==='all'||(layer==='groups')===(t.kind==='teaching-group'))&&(!only||favoriteIds.includes(t.id))&&normalize([t.scientificName,...t.commonNames,...(t.aliases??[]),...(t.currentAcceptedNames??[]),...(t.currentGenera??[])].join(' ')).includes(normalize(query))),[taxa,query,only,favoriteIds,layer]);
 const index=visible.findIndex(t=>t.id===selected),current=taxa.find(t=>t.id===selected);
 function open(id:string){lastRead.current=id;setSelected(id);onResumeChange(id);}
 function toggleFavorite(t:StudyTaxon){const removing=favoriteIds.includes(t.id),nextIds=removing?favoriteIds.filter(id=>id!==t.id):[...favoriteIds,t.id];if(removing&&only&&selected===t.id){const oldIndex=visible.findIndex(item=>item.id===t.id),remaining=visible.filter(item=>item.id!==t.id),next=remaining[Math.min(Math.max(oldIndex,0),remaining.length-1)];if(next)open(next.id);else{setSelected(null);Alert.alert('Preferito rimosso','Nessuna scheda corrisponde ai filtri attivi. Disattiva Preferiti o modifica la ricerca per continuare.');}}onFavoriteIdsChange(nextIds);}
 const favorite=(t:StudyTaxon)=><Button label={favoriteIds.includes(t.id)?'Rimuovi preferito':'Salva preferito'} onPress={()=>toggleFavorite(t)}/>;
 const notice=null;
 const detailView=current?<Modal visible animationType="slide" onRequestClose={()=>setSelected(null)}><SafeAreaView style={s.screen}><View style={s.toolbar}><Button label="Torna alle schede" onPress={()=>setSelected(null)}/><Text style={s.small}>{index>=0?(index+1)+' / '+visible.length+' schede':'Scheda fuori dai filtri'}</Text><View style={s.row}><Button label="← Precedente" disabled={index<=0} onPress={()=>open(visible[index-1].id)}/><Button label="Successiva →" disabled={index<0||index>=visible.length-1} onPress={()=>open(visible[index+1].id)}/></View></View><ScrollView key={current.id} contentContainerStyle={s.list}>{notice}{favorite(current)}<Content taxon={current}/>{current.relatedIds?.map(id=>{const child=taxa.find(t=>t.id===id);return child?<Button key={id} label={'Studia '+child.scientificName} onPress={()=>{setLayer('minimum');setQuery('');setOnly(false);open(id);}}/>:null;})}</ScrollView></SafeAreaView></Modal>:null;
 const header=<View style={[s.content,s.header]}><Text style={s.title}>Studio e atlante</Text>{notice}<TextInput accessibilityLabel="Cerca nome scientifico, comune o sinonimo" placeholder="Nome scientifico, comune o sinonimo" value={query} onChangeText={setQuery} style={s.input} autoCorrect={false}/><View style={s.row}><Button label={feed?'Tap':'Scorri'} selected={feed} onPress={()=>setFeed(!feed)}/><Button label="Preferiti" selected={only} onPress={()=>setOnly(!only)}/><Button label={(layer==='minimum'?'Minimo':layer==='groups'?'Gruppi':'Tutte')+' ▾'} selected={layer!=='minimum'} onPress={()=>setFilters(true)}/></View>{resumeId&&<Button label="Riprendi ultima scheda" disabled={!taxa.some(t=>t.id===resumeId)} onPress={()=>{if(resumeId){setQuery('');setOnly(false);setLayer('all');open(resumeId);}}}/>}<Text accessibilityLiveRegion="polite" style={s.small}>{visible.length} schede · {favoriteIds.length} {favoriteIds.length===1?'preferito':'preferiti'}</Text></View>;
 return <View style={s.screen}><FlatList viewabilityConfig={readingConfig} onViewableItemsChanged={readingChanged} data={visible} keyExtractor={t=>t.id} ListHeaderComponent={header} initialNumToRender={6} maxToRenderPerBatch={6} windowSize={7} extraData={{feed,favoriteIds}} keyboardShouldPersistTaps="handled" contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.text}>Nessuna scheda corrisponde ai filtri.</Text>} renderItem={({item:t})=><View style={s.card}>{feed?<>{favorite(t)}<Content taxon={t}/><Button label="Apri dettaglio" onPress={()=>open(t.id)}/></>:<Pressable accessibilityRole="button" accessibilityLabel={'Apri '+t.scientificName} onPress={()=>open(t.id)} style={s.tap}><Text style={s.heading}>{t.commonNames[0]||t.scientificName}</Text>{!!t.commonNames[0]&&<Text style={s.common}>{t.scientificName}</Text>}<Text style={s.small}>{favoriteIds.includes(t.id)?'★ Preferito · ':''}{ranks[t.rank??'']??t.rank??'Rango da documentare'} · Apri scheda →</Text></Pressable>}</View>}/>{detailView}{filters&&<Modal visible animationType="slide" onRequestClose={()=>setFilters(false)}><SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.list}><Text style={s.title}>Scegli il catalogo</Text><Text style={s.text}>Le unità minime e le schede di genere o gruppo sono livelli didattici distinti.</Text><Button label={`Minimo (${taxa.filter(t=>t.kind!=='teaching-group').length})`} selected={layer==='minimum'} onPress={()=>{setLayer('minimum');setFilters(false);}}/><Button label={`Generi e gruppi (${taxa.filter(t=>t.kind==='teaching-group').length})`} selected={layer==='groups'} onPress={()=>{setLayer('groups');setFilters(false);}}/><Button label={`Tutte (${taxa.length})`} selected={layer==='all'} onPress={()=>{setLayer('all');setFilters(false);}}/><Button label="Chiudi" onPress={()=>setFilters(false)}/></ScrollView></SafeAreaView></Modal>}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#f4f7f2'},list:{padding:16,paddingBottom:40},content:{gap:12,paddingBottom:16},header:{gap:8},title:{fontSize:24,fontWeight:'800',color:'#174f2b'},name:{fontSize:25,fontStyle:'italic',fontWeight:'700',color:'#174f2b'},common:{fontSize:18,color:'#31583c'},heading:{fontSize:19,fontWeight:'700',color:'#14261a'},text:{fontSize:16,lineHeight:24,color:'#243f2c'},small:{fontSize:14,lineHeight:21,color:'#435c49'},notice:{fontSize:14,lineHeight:21,color:'#624c12',backgroundColor:'#fff6db',padding:12,borderRadius:12},input:{minHeight:48,padding:12,borderWidth:1,borderColor:'#708576',borderRadius:12,backgroundColor:'white',fontSize:16},row:{flexDirection:'row',flexWrap:'wrap',gap:8},button:{minHeight:48,padding:12,justifyContent:'center',borderRadius:12,borderWidth:1,borderColor:'#174f2b',backgroundColor:'white',marginVertical:3},buttonText:{fontSize:16,fontWeight:'600',color:'#174f2b'},disabled:{opacity:.45},selectedButton:{backgroundColor:'#e0eddc',borderWidth:2},card:{backgroundColor:'white',padding:16,borderRadius:16,marginVertical:8,borderWidth:1,borderColor:'#c6d3c5'},tap:{minHeight:70,gap:8},toolbar:{padding:12,gap:8},source:{gap:6,borderTopWidth:1,borderTopColor:'#d5dfd3',paddingTop:10}});
