import React,{useMemo,useRef,useState} from 'react';
import {FlatList,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
const ranks:Record<string,string>={species:'Specie',genus:'Genere',section:'Sezione',group:'Gruppo',speciesGroup:'Gruppo di specie',aggregate:'Aggregato',operationalGroup:'Gruppo operativo',family:'Famiglia',subgenus:'Sottogenere',subsection:'Sottosezione',subspecies:'Sottospecie',variety:'Varietà'};
export type StudyTaxon={id:string;scientificName:string;commonNames:string[];summary:string;characters:string[];lookalikes:string[];habitat:string[];sources:{title:string;location?:string;url?:string|null;supportedClaim?:string;notes?:string|null}[];aliases?:string[];rank?:string;currentAcceptedNames?:string[];diagnosticStatus?:string};
type Props={taxa:StudyTaxon[];favoriteIds:string[];onFavoriteIdsChange:(ids:string[])=>void;resumeId:string|null;onResumeChange:(id:string)=>void;catalogVersion:string};
const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('it').trim();
function Button({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>;}
function Content({taxon:t}:{taxon:StudyTaxon}){return <View style={s.content}><Text accessibilityRole="header" style={s.name}>{t.scientificName}</Text><Text style={s.common}>{t.commonNames.join(' · ')}</Text><Text style={s.small}>Rango: {ranks[t.rank??'']??t.rank??'da documentare'}</Text>{!!t.currentAcceptedNames?.length&&t.rank!=='species'&&<Text style={s.small}>Nomi compresi nel concetto didattico: {t.currentAcceptedNames.join(' · ')}</Text>}<Text style={s.text}>{t.summary}</Text><Text style={s.heading}>Caratteri di studio</Text>{t.characters.map((c,i)=><Text key={i} style={s.text}>{i+1}. {c}</Text>)}<Text style={s.heading}>Confronti e habitat</Text><Text style={s.text}>{t.lookalikes.length?t.lookalikes.join('\n'):'Confusioni specifiche non documentate in questa versione: non significa che siano assenti.'}</Text><Text style={s.text}>{t.habitat.join(' · ')||'Habitat da documentare.'}</Text><Text style={s.heading}>Fonti e limiti</Text>{t.sources.map((source,i)=><View key={i} style={s.source}><Text selectable style={s.text}>{source.title}{source.location?' · '+source.location:''}</Text>{!!source.supportedClaim&&<Text style={s.small}>{source.supportedClaim}</Text>}{!!source.notes&&<Text style={s.small}>{source.notes}</Text>}{!!source.url&&<Text selectable style={s.small}>{source.url}</Text>}</View>)}</View>;}
export default function Studio({taxa,favoriteIds,onFavoriteIdsChange,resumeId,onResumeChange,catalogVersion}:Props){
 const [query,setQuery]=useState(''),[only,setOnly]=useState(false),[feed,setFeed]=useState(false),[selected,setSelected]=useState<string|null>(null);
 const visible=useMemo(()=>taxa.filter(t=>(!only||favoriteIds.includes(t.id))&&normalize([t.scientificName,...t.commonNames,...(t.aliases??[])].join(' ')).includes(normalize(query))),[taxa,query,only,favoriteIds]);
 const index=visible.findIndex(t=>t.id===selected),current=taxa.find(t=>t.id===selected);
 function open(id:string){setSelected(id);onResumeChange(id);}
 const favorite=(t:StudyTaxon)=><Button label={favoriteIds.includes(t.id)?'Rimuovi preferito':'Salva preferito'} onPress={()=>onFavoriteIdsChange(favoriteIds.includes(t.id)?favoriteIds.filter(id=>id!==t.id):[...favoriteIds,t.id])}/>;
 const notice=<Text style={s.notice}>Profili didattici con audit interno. Revisione micologica indipendente pendente. La scheda non certifica un’identificazione né autorizza il consumo.</Text>;
 const detailView=current?<Modal visible animationType="slide" onRequestClose={()=>setSelected(null)}><SafeAreaView style={s.screen}><View style={s.toolbar}><Button label="Torna alle schede" onPress={()=>setSelected(null)}/><Text style={s.small}>{index>=0?(index+1)+' / '+visible.length+' schede':'Scheda fuori dai filtri'}</Text><View style={s.row}><Button label="← Precedente" disabled={index<=0} onPress={()=>open(visible[index-1].id)}/><Button label="Successiva →" disabled={index<0||index>=visible.length-1} onPress={()=>open(visible[index+1].id)}/></View></View><ScrollView key={current.id} contentContainerStyle={s.list}>{notice}{favorite(current)}<Content taxon={current}/></ScrollView></SafeAreaView></Modal>:null;
 const header=<View style={s.content}><Text style={s.title}>Studio e atlante</Text><Text style={s.small}>{catalogVersion} · consultazione offline</Text>{notice}<TextInput accessibilityLabel="Cerca nome scientifico, comune o sinonimo" placeholder="Nome scientifico, comune o sinonimo" value={query} onChangeText={setQuery} style={s.input} autoCorrect={false}/><View style={s.row}><Button label={feed?'Passa al tap':'Studio con scrolling'} onPress={()=>setFeed(!feed)}/><Button label={only?'Tutte le schede':'Solo preferiti'} onPress={()=>setOnly(!only)}/></View><Button label="Riprendi ultima scheda" disabled={!taxa.some(t=>t.id===resumeId)} onPress={()=>{if(resumeId){setQuery('');setOnly(false);open(resumeId);}}}/><Text accessibilityLiveRegion="polite" style={s.small}>{visible.length} schede · {favoriteIds.length} preferiti</Text></View>;
 return <View style={s.screen}><FlatList data={visible} keyExtractor={t=>t.id} ListHeaderComponent={header} initialNumToRender={6} maxToRenderPerBatch={6} windowSize={7} extraData={{feed,favoriteIds}} keyboardShouldPersistTaps="handled" contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.text}>Nessuna scheda corrisponde ai filtri.</Text>} renderItem={({item:t})=><View style={s.card}>{feed?<>{favorite(t)}<Content taxon={t}/><Button label="Apri dettaglio" onPress={()=>open(t.id)}/></>:<Pressable accessibilityRole="button" accessibilityLabel={'Apri '+t.scientificName} onPress={()=>open(t.id)} style={s.tap}><Text style={s.heading}>{t.commonNames[0]||t.scientificName}</Text><Text style={s.common}>{t.scientificName}</Text><Text style={s.small}>{favoriteIds.includes(t.id)?'★ Preferito · ':''}{ranks[t.rank??'']??t.rank??'Rango da documentare'} · Apri scheda →</Text></Pressable>}</View>}/>{detailView}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#f4f7f2'},list:{padding:16,paddingBottom:40},content:{gap:12,paddingBottom:16},title:{fontSize:28,fontWeight:'800',color:'#174f2b'},name:{fontSize:25,fontStyle:'italic',fontWeight:'700',color:'#174f2b'},common:{fontSize:18,color:'#31583c'},heading:{fontSize:19,fontWeight:'700',color:'#14261a'},text:{fontSize:16,lineHeight:24,color:'#243f2c'},small:{fontSize:14,lineHeight:21,color:'#435c49'},notice:{fontSize:14,lineHeight:21,color:'#624c12',backgroundColor:'#fff6db',padding:12,borderRadius:12},input:{minHeight:48,padding:12,borderWidth:1,borderColor:'#708576',borderRadius:12,backgroundColor:'white',fontSize:16},row:{flexDirection:'row',flexWrap:'wrap',gap:8},button:{minHeight:48,padding:12,justifyContent:'center',borderRadius:12,borderWidth:1,borderColor:'#174f2b',backgroundColor:'white',marginVertical:3},buttonText:{fontSize:16,fontWeight:'600',color:'#174f2b'},disabled:{opacity:.45},card:{backgroundColor:'white',padding:16,borderRadius:16,marginVertical:8,borderWidth:1,borderColor:'#c6d3c5'},tap:{minHeight:70,gap:8},toolbar:{padding:12,gap:8},source:{gap:6,borderTopWidth:1,borderTopColor:'#d5dfd3',paddingTop:10}});
