import type { Area } from "./domain.ts";

type AreaSeed = readonly [
  id: string,
  name: string,
  region: string,
  latitude: number,
  longitude: number,
  habitats: string[],
  expectedTaxa: string[],
];

const seeds: AreaSeed[] = [
  ["gran-paradiso-vda", "Gran Paradiso valdostano", "Valle d'Aosta", 45.61, 7.3, ["Abete rosso", "Larice", "Prati alpini"], ["boletus-edulis", "hygrophorus-marzuolus"]],
  ["val-dayas", "Val d'Ayas e Monte Rosa", "Valle d'Aosta", 45.82, 7.73, ["Abete rosso", "Larice", "Prati alpini"], ["boletus-edulis", "amanita-vaginatae"]],
  ["valli-cuneesi", "Valli cuneesi", "Piemonte", 44.36, 7.36, ["Faggeta", "Abete bianco", "Castagneto"], ["boletus-edulis", "russula-cyanoxantha"]],
  ["monferrato", "Monferrato boschivo", "Piemonte", 44.98, 8.35, ["Querceto", "Castagneto", "Pioppeto"], ["russula-virescens", "cyclocybe-cylindracea"]],
  ["valsesia", "Valsesia e Biellese", "Piemonte", 45.68, 8.06, ["Faggeta", "Castagneto", "Abete rosso"], ["boletus-edulis", "craterellus-cornucopioides"]],
  ["beigua", "Beigua e Appennino ligure", "Liguria", 44.43, 8.56, ["Faggeta", "Castagneto", "Pineta"], ["boletus-edulis", "lactarius-deliciosi"]],
  ["val-di-vara", "Val di Vara", "Liguria", 44.28, 9.63, ["Castagneto", "Querceto", "Faggeta"], ["boletus-edulis", "russula-vesca"]],
  ["valtellina", "Valtellina e Orobie", "Lombardia", 46.08, 9.76, ["Abete rosso", "Abete bianco", "Faggeta"], ["boletus-edulis", "hygrophorus-marzuolus"]],
  ["prealpi-bergamasche", "Prealpi bergamasche", "Lombardia", 45.88, 9.86, ["Faggeta", "Castagneto", "Abete rosso"], ["boletus-edulis", "craterellus-cornucopioides"]],
  ["oltrepo-pavese", "Oltrepò pavese", "Lombardia", 44.91, 9.18, ["Querceto", "Castagneto", "Prati"], ["russula-virescens", "agaricus-campestris-group"]],
  ["fiemme-fassa", "Fiemme e Fassa", "Trentino-Alto Adige", 46.31, 11.55, ["Abete rosso", "Larice", "Abete bianco"], ["boletus-edulis", "tricholoma-terreum-group"]],
  ["cansiglio", "Cansiglio e Alpago", "Veneto", 46.08, 12.42, ["Faggeta", "Abete bianco", "Abete rosso"], ["boletus-edulis", "hygrophorus-marzuolus"]],
  ["lessinia", "Lessinia", "Veneto", 45.61, 11.1, ["Faggeta", "Prati montani", "Carpino"], ["russula-cyanoxantha", "marasmius-oreades"]],
  ["cadore", "Cadore e Comelico", "Veneto", 46.55, 12.43, ["Abete rosso", "Larice", "Faggeta"], ["boletus-edulis", "amanita-vaginatae"]],
  ["carnia", "Carnia e Tarvisiano", "Friuli-Venezia Giulia", 46.48, 13.03, ["Abete rosso", "Abete bianco", "Faggeta"], ["boletus-edulis", "hygrophorus-marzuolus"]],
  ["carso", "Carso e Valli del Natisone", "Friuli-Venezia Giulia", 45.95, 13.52, ["Querceto", "Carpino nero", "Prati carsici"], ["russula-vesca", "agaricus-campestris-group"]],
  ["appennino-parmense", "Appennino parmense", "Emilia-Romagna", 44.49, 10.02, ["Faggeta", "Castagneto", "Abete bianco"], ["boletus-edulis", "russula-cyanoxantha"]],
  ["amiata", "Monte Amiata", "Toscana", 42.89, 11.63, ["Faggeta", "Castagneto", "Querceto"], ["boletus-edulis", "hygrophorus-russula"]],
  ["valnerina", "Valnerina e Monti Martani", "Umbria", 42.82, 12.91, ["Faggeta", "Querceto", "Prati montani"], ["boletus-edulis", "marasmius-oreades"]],
  ["monte-cucco", "Monte Cucco", "Umbria", 43.37, 12.74, ["Faggeta", "Querceto", "Prati"], ["russula-cyanoxantha", "craterellus-cornucopioides"]],
  ["sibillini-marche", "Sibillini marchigiani", "Marche", 42.91, 13.21, ["Faggeta", "Querceto", "Prati montani"], ["boletus-edulis", "marasmius-oreades"]],
  ["montefeltro", "Montefeltro e Catria", "Marche", 43.62, 12.55, ["Faggeta", "Querceto", "Castagneto"], ["boletus-edulis", "russula-vesca"]],
  ["simbruini", "Monti Simbruini", "Lazio", 41.95, 13.13, ["Faggeta", "Querceto", "Prati montani"], ["boletus-edulis", "craterellus-cornucopioides"]],
  ["gran-sasso", "Gran Sasso e Laga", "Abruzzo", 42.47, 13.47, ["Faggeta", "Querceto", "Prati montani"], ["boletus-edulis", "marasmius-oreades"]],
  ["maiella", "Maiella", "Abruzzo", 42.06, 14.05, ["Faggeta", "Pino nero", "Prati montani"], ["boletus-edulis", "lactarius-deliciosi"]],
  ["matese-molise", "Matese molisano", "Molise", 41.48, 14.4, ["Faggeta", "Querceto", "Prati"], ["boletus-edulis", "agaricus-campestris-group"]],
  ["alto-molise", "Alto Molise", "Molise", 41.79, 14.25, ["Abete bianco", "Faggeta", "Querceto"], ["boletus-edulis", "hygrophorus-marzuolus"]],
  ["matese-campano", "Matese campano", "Campania", 41.36, 14.38, ["Faggeta", "Querceto", "Prati"], ["boletus-edulis", "agaricus-campestris-group"]],
  ["monti-picentini", "Monti Picentini", "Campania", 40.78, 15.03, ["Faggeta", "Castagneto", "Querceto"], ["boletus-edulis", "russula-virescens"]],
  ["cilento-interno", "Cilento interno", "Campania", 40.29, 15.37, ["Faggeta", "Querceto", "Castagneto"], ["boletus-edulis", "russula-vesca"]],
  ["gargano", "Foresta Umbra e Gargano", "Puglia", 41.82, 15.99, ["Faggeta", "Querceto", "Pineta"], ["boletus-edulis", "lactarius-deliciosi"]],
  ["murgia", "Alta Murgia", "Puglia", 40.96, 16.39, ["Pascoli", "Querceto", "Pineta"], ["pleurotus-eryngii", "agaricus-campestris-group"]],
  ["vulture", "Vulture e Alto Bradano", "Basilicata", 40.95, 15.62, ["Faggeta", "Castagneto", "Querceto"], ["boletus-edulis", "russula-virescens"]],
  ["aspromonte", "Aspromonte", "Calabria", 38.16, 15.9, ["Faggeta", "Abete bianco", "Pino laricio"], ["boletus-edulis", "lactarius-deliciosi"]],
  ["nebrodi", "Nebrodi", "Sicilia", 37.94, 14.69, ["Faggeta", "Querceto", "Pascoli"], ["boletus-edulis", "pleurotus-eryngii"]],
  ["etna", "Etna e versanti boschivi", "Sicilia", 37.73, 15.0, ["Pineta", "Querceto", "Castagneto"], ["lactarius-deliciosi", "russula-virescens"]],
  ["limbara", "Limbara e Gallura interna", "Sardegna", 40.86, 9.12, ["Querceto", "Sughereta", "Castagneto"], ["russula-virescens", "amanita-vaginatae"]],
];


const verifiedAreaAdditions: Area[] = [
  {
    id: "parco-aveto",
    name: "Val d'Aveto e valli del Parco",
    region: "Liguria",
    center: [44.53, 9.39],
    habitat: ["Faggeta", "Castagneto", "Cerreta", "Boschi montani"],
    moisture: 78,
    temperatureFit: 76,
    seasonFit: 82,
    verifiedSignals: 88,
    delayedVisitors: 6,
    lastUpdatedLabel: "fonti ufficiali territoriali verificate",
    expectedTaxa: ["boletus-edulis", "russula-cyanoxantha", "craterellus-cornucopioides"],
    reasons: [
      "Il Parco indica il porcino come prodotto naturale diffuso in tutte le valli",
      "Raccolta documentata in boschi di castagno, cerro, faggio, carpino e frassino",
    ],
    elevationRangeM: [350, 1800],
    evidenceSources: [
      {
        label: "Parco Aveto — Funghi porcini",
        url: "https://www.parks.it/parco.aveto/dettaglio_prodotto.php?id_prodotti=3175",
        kind: "official-park",
      },
      {
        label: "Parco Aveto — Per funghi nel Parco",
        url: "https://www.parks.it/parco.aveto/page.php?id=209",
        kind: "official-park",
      },
    ],
  },
  {
    id: "cerreto-reggiano",
    name: "Cerreto e Appennino reggiano",
    region: "Emilia-Romagna",
    center: [44.31, 10.22],
    habitat: ["Faggeta", "Abete bianco", "Boschi appenninici", "Prati montani"],
    moisture: 80,
    temperatureFit: 78,
    seasonFit: 86,
    verifiedSignals: 92,
    delayedVisitors: 12,
    lastUpdatedLabel: "fonti ufficiali territoriali verificate",
    expectedTaxa: ["boletus-edulis", "russula-cyanoxantha", "hygrophorus-marzuolus"],
    reasons: [
      "Sede del Campionato Mondiale del Fungo dedicato alla ricerca del porcino",
      "Il Parco documenta la stagione micologica nei boschi di faggi e abeti intorno a Cerreto",
    ],
    elevationRangeM: [750, 1900],
    evidenceSources: [
      {
        label: "Parco Appennino — Campionato Mondiale del Fungo 2026",
        url: "https://www.parcoappennino.it/campionato.mondiale.fungo/pagina.php?id=297",
        kind: "official-park",
      },
      {
        label: "Parco Appennino — nascita dei funghi a Cerreto",
        url: "https://www.parcoappennino.it/newsdettaglio.php?id=88073",
        kind: "official-park",
      },
    ],
  },
  {
    id: "corno-scale",
    name: "Corno alle Scale e Alto Reno",
    region: "Emilia-Romagna",
    center: [44.13, 10.84],
    habitat: ["Faggeta", "Castagneto", "Boschi montani", "Prati"],
    moisture: 77,
    temperatureFit: 77,
    seasonFit: 82,
    verifiedSignals: 80,
    delayedVisitors: 8,
    lastUpdatedLabel: "fonti ufficiali territoriali verificate",
    expectedTaxa: ["boletus-edulis", "hygrophorus-marzuolus", "russula-cyanoxantha"],
    reasons: [
      "Il Parco dispone di regolamento specifico per la raccolta dei prodotti del sottobosco",
      "Sono organizzate escursioni micologiche nei boschi del Parco",
    ],
    elevationRangeM: [650, 1945],
    evidenceSources: [
      {
        label: "Regolamento sottobosco Corno alle Scale",
        url: "https://www.parks.it/riserva.contrafforte.pliocenico/dettaglio.php?id=87507",
        kind: "official-park",
      },
      {
        label: "Corno alle Scale — escursione micologica",
        url: "https://www.parks.it/parco.corno.scale/man_dettaglio.php?id=142727",
        kind: "official-park",
      },
    ],
  },
  {
    id: "garfagnana",
    name: "Garfagnana e Appennino lucchese",
    region: "Toscana",
    center: [44.05, 10.42],
    habitat: ["Castagneto", "Faggeta", "Querceto", "Boschi appenninici"],
    moisture: 77,
    temperatureFit: 79,
    seasonFit: 82,
    verifiedSignals: 72,
    delayedVisitors: 8,
    lastUpdatedLabel: "fonti regionali verificate",
    expectedTaxa: ["boletus-edulis", "russula-virescens", "craterellus-cornucopioides"],
    reasons: [
      "La Regione Toscana adotta limitazioni specifiche alla raccolta in comuni della Garfagnana",
      "L'area presenta continuità di castagneti e faggete montane",
    ],
    elevationRangeM: [300, 1800],
    evidenceSources: [
      {
        label: "Regione Toscana — limitazioni raccolta funghi Garfagnana",
        url: "https://www301.regione.toscana.it/bancadati/atti/Contenuto.xml?id=5416823&nomeFile=Delibera_n.471_del_22-04-2024",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "adamello-valcamonica",
    name: "Adamello e alta Val Camonica",
    region: "Lombardia",
    center: [46.05, 10.42],
    habitat: ["Abete rosso", "Larice", "Faggeta", "Boschi subalpini"],
    moisture: 79,
    temperatureFit: 71,
    seasonFit: 74,
    verifiedSignals: 76,
    delayedVisitors: 8,
    lastUpdatedLabel: "fonti ufficiali territoriali verificate",
    expectedTaxa: ["boletus-edulis", "amanita-vaginatae", "tricholoma-terreum-group"],
    reasons: [
      "Il Parco dell'Adamello dispone di un regolamento specifico per la raccolta dei funghi",
      "Area montana con forte gradiente altitudinale e vasti boschi alpini",
    ],
    elevationRangeM: [700, 2200],
    evidenceSources: [
      {
        label: "Parco Adamello — regolamento raccolta funghi",
        url: "https://www.parcoadamello.it/ente-gestore/regolamenti-e-normative/piani-di-settore-e-regolamenti",
        kind: "official-park",
      },
    ],
  },
  {
    id: "asiago-sette-comuni",
    name: "Altopiano di Asiago e Sette Comuni",
    region: "Veneto",
    center: [45.88, 11.51],
    habitat: ["Abete rosso", "Faggeta", "Prati montani", "Boschi misti"],
    moisture: 74,
    temperatureFit: 73,
    seasonFit: 76,
    verifiedSignals: 70,
    delayedVisitors: 9,
    lastUpdatedLabel: "fonti comunali verificate",
    expectedTaxa: ["boletus-edulis", "tricholoma-terreum-group", "marasmius-oreades"],
    reasons: [
      "Il Comune di Asiago disciplina esplicitamente le zone di raccolta dei funghi",
      "Mosaico di boschi montani e prati dell'altopiano",
    ],
    elevationRangeM: [900, 1800],
    evidenceSources: [
      {
        label: "Comune di Asiago — regolamento raccolta funghi",
        url: "https://www.comune.asiago.vi.it/wp-content/uploads/2023/09/74-regolamenti-regolamento-comunale-di-polizia-rurale.pdf",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "prealpi-giulie",
    name: "Prealpi Giulie e Val Resia",
    region: "Friuli-Venezia Giulia",
    center: [46.33, 13.30],
    habitat: ["Faggeta", "Pino nero", "Mugheta", "Praterie alpine"],
    moisture: 82,
    temperatureFit: 69,
    seasonFit: 72,
    verifiedSignals: 68,
    delayedVisitors: 5,
    lastUpdatedLabel: "fonti ufficiali habitat verificate",
    expectedTaxa: ["boletus-edulis", "amanita-vaginatae", "russula-cyanoxantha"],
    reasons: [
      "Il Parco documenta faggete miste, pinete e forte gradiente altitudinale",
      "Area vasta e poco urbanizzata: segnale ecologico, non fungaia puntuale",
    ],
    elevationRangeM: [350, 2587],
    evidenceSources: [
      {
        label: "Parco Prealpi Giulie — territorio e habitat",
        url: "https://www.parks.it/parco.prealpi.giulie/index.html",
        kind: "official-park",
      },
    ],
  },
  {
    id: "pnalm-marsica",
    name: "Marsica e Parco d'Abruzzo-Lazio-Molise",
    region: "Abruzzo",
    center: [41.86, 13.79],
    habitat: ["Faggeta", "Querceto", "Prati montani", "Boschi appenninici"],
    moisture: 74,
    temperatureFit: 75,
    seasonFit: 76,
    verifiedSignals: 74,
    delayedVisitors: 7,
    lastUpdatedLabel: "fonti ufficiali territoriali verificate",
    expectedTaxa: ["boletus-edulis", "russula-cyanoxantha", "marasmius-oreades"],
    reasons: [
      "Grande area protetta appenninica con continuità forestale e forte gradiente altitudinale",
      "La valutazione rimane aggregata e subordinata ai regolamenti del Parco",
    ],
    elevationRangeM: [700, 2200],
    evidenceSources: [
      {
        label: "Parco d'Abruzzo Lazio Molise — Piano del Parco",
        url: "https://www.parcoabruzzo.it/pagina.php?id=424",
        kind: "official-park",
      },
    ],
  },
  {
    id: "sasso-simone",
    name: "Sasso Simone, Simoncello e Carpegna",
    region: "Marche",
    center: [43.80, 12.32],
    habitat: ["Faggeta", "Querceto", "Prati montani", "Boschi appenninici"],
    moisture: 72,
    temperatureFit: 77,
    seasonFit: 79,
    verifiedSignals: 80,
    delayedVisitors: 7,
    lastUpdatedLabel: "fonti ufficiali territoriali verificate",
    expectedTaxa: ["boletus-edulis", "russula-vesca", "marasmius-oreades"],
    reasons: [
      "Il Parco gestisce un'autorizzazione specifica per ricerca e raccolta dei funghi",
      "Macroarea interregionale Marche-Emilia-Romagna, senza punti di raccolta pubblicati",
    ],
    elevationRangeM: [500, 1415],
    evidenceSources: [
      {
        label: "Parco Sasso Simone e Simoncello — raccolta funghi",
        url: "https://parcosimone.it/notizie/3486482/norme-raccolta-funghi",
        kind: "official-park",
      },
    ],
  },
  {
    id: "reventino",
    name: "Reventino e Presila catanzarese",
    region: "Calabria",
    center: [39.06, 16.31],
    habitat: ["Castagneto", "Faggeta", "Querceto", "Boschi montani"],
    moisture: 72,
    temperatureFit: 80,
    seasonFit: 79,
    verifiedSignals: 58,
    delayedVisitors: 4,
    lastUpdatedLabel: "segnale micologico territoriale verificato",
    expectedTaxa: ["boletus-edulis", "russula-virescens", "lactarius-deliciosi"],
    reasons: [
      "Presenza di un gruppo micologico UMI specificamente radicato nel Reventino",
      "Segnale associativo usato solo per priorità territoriale, non come prova di produttività puntuale",
    ],
    elevationRangeM: [500, 1450],
    evidenceSources: [
      {
        label: "UMI — Gruppo Micologico Reventino",
        url: "https://www.unionemicologicaitaliana-aps.it/gruppi-micologici/",
        kind: "mycological-association",
      },
    ],
  },
  {
    id: "canal-ferro-val-canale",
    name: "Canal del Ferro e Val Canale",
    region: "Friuli-Venezia Giulia",
    center: [46.45, 13.18],
    habitat: ["Abete rosso", "Abete bianco", "Faggeta", "Boschi alpini"],
    moisture: 82,
    temperatureFit: 70,
    seasonFit: 74,
    verifiedSignals: 78,
    delayedVisitors: 7,
    lastUpdatedLabel: "raccolta territoriale ufficialmente regolamentata",
    expectedTaxa: ["boletus-edulis", "hygrophorus-marzuolus", "amanita-vaginatae"],
    reasons: [
      "La Regione FVG gestisce permessi specifici di raccolta per Canal del Ferro e Val Canale",
      "Ampia continuità di foreste montane e forte gradiente altitudinale",
    ],
    elevationRangeM: [450, 1900],
    evidenceSources: [
      {
        label: "Regione FVG — raccolta funghi, Canal del Ferro e Val Canale",
        url: "https://www.regione.fvg.it/rafvg/cms/RAFVG/economia-imprese/agricoltura-foreste/raccolta-funghi/",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "dolomiti-friulane-cavallo",
    name: "Dolomiti Friulane, Cavallo e Cansiglio friulano",
    region: "Friuli-Venezia Giulia",
    center: [46.20, 12.56],
    habitat: ["Faggeta", "Abete bianco", "Abete rosso", "Boschi montani"],
    moisture: 80,
    temperatureFit: 71,
    seasonFit: 75,
    verifiedSignals: 76,
    delayedVisitors: 6,
    lastUpdatedLabel: "raccolta territoriale ufficialmente regolamentata",
    expectedTaxa: ["boletus-edulis", "hygrophorus-marzuolus", "russula-cyanoxantha"],
    reasons: [
      "La Regione FVG individua una specifica area autorizzativa Dolomiti Friulane, Cavallo e Cansiglio",
      "Macroarea forestale ampia, usata solo come indicatore territoriale aggregato",
    ],
    elevationRangeM: [300, 2100],
    evidenceSources: [
      {
        label: "Regione FVG — raccolta funghi nelle Comunità di montagna",
        url: "https://www.regione.fvg.it/rafvg/cms/RAFVG/economia-imprese/agricoltura-foreste/raccolta-funghi/",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "pasubio-piccole-dolomiti",
    name: "Pasubio e Piccole Dolomiti",
    region: "Veneto",
    center: [45.73, 11.20],
    habitat: ["Faggeta", "Abete rosso", "Prati montani", "Boschi misti"],
    moisture: 73,
    temperatureFit: 73,
    seasonFit: 76,
    verifiedSignals: 66,
    delayedVisitors: 7,
    lastUpdatedLabel: "area di raccolta regionale verificata",
    expectedTaxa: ["boletus-edulis", "russula-cyanoxantha", "marasmius-oreades"],
    reasons: [
      "La Regione Veneto elenca l'Unione Montana Pasubio-Piccole Dolomiti fra gli enti competenti per la raccolta",
      "Boschi montani e praterie con forte variabilità altitudinale",
    ],
    elevationRangeM: [500, 2000],
    evidenceSources: [
      {
        label: "Regione Veneto — raccolta funghi",
        url: "https://www.regione.veneto.it/web/enti-locali/raccolta-funghi",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "monte-baldo",
    name: "Monte Baldo e alta Val d'Adige",
    region: "Veneto",
    center: [45.62, 10.84],
    habitat: ["Faggeta", "Prati montani", "Boschi misti", "Querceto"],
    moisture: 68,
    temperatureFit: 75,
    seasonFit: 73,
    verifiedSignals: 62,
    delayedVisitors: 6,
    lastUpdatedLabel: "foreste demaniali e raccolta regionale verificate",
    expectedTaxa: ["boletus-edulis", "russula-cyanoxantha", "marasmius-oreades"],
    reasons: [
      "La Regione Veneto include la Foresta del Monte Baldo nel demanio forestale regionale",
      "L'area è mantenuta come macroarea ecologica, non come localizzazione di raccolta",
    ],
    elevationRangeM: [500, 2000],
    evidenceSources: [
      {
        label: "Regione Veneto — raccolta funghi e foreste demaniali",
        url: "https://www.regione.veneto.it/web/enti-locali/raccolta-funghi",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "lunigiana-appennino",
    name: "Lunigiana e Appennino tosco-ligure",
    region: "Toscana",
    center: [44.27, 9.93],
    habitat: ["Castagneto", "Faggeta", "Querceto", "Boschi appenninici"],
    moisture: 80,
    temperatureFit: 78,
    seasonFit: 84,
    verifiedSignals: 64,
    delayedVisitors: 7,
    lastUpdatedLabel: "raccolta regionale verificata, habitat aggregati",
    expectedTaxa: ["boletus-edulis", "craterellus-cornucopioides", "russula-cyanoxantha"],
    reasons: [
      "La raccolta dei funghi è regolamentata a scala regionale con limitazioni territoriali aggiornate",
      "Continuità di castagneti e faggete dell'Appennino tosco-ligure",
    ],
    elevationRangeM: [250, 1700],
    evidenceSources: [
      {
        label: "Regione Toscana — raccolta funghi e limitazioni territoriali",
        url: "https://www.regione.toscana.it/it/-/raccolta-funghi-ecco-le-disposizioni",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "mugello-alto-mugello",
    name: "Mugello e Alto Mugello",
    region: "Toscana",
    center: [44.02, 11.39],
    habitat: ["Faggeta", "Castagneto", "Querceto", "Boschi appenninici"],
    moisture: 76,
    temperatureFit: 80,
    seasonFit: 81,
    verifiedSignals: 63,
    delayedVisitors: 8,
    lastUpdatedLabel: "raccolta regionale verificata, habitat aggregati",
    expectedTaxa: ["boletus-edulis", "craterellus-cornucopioides", "russula-vesca"],
    reasons: [
      "Territorio appenninico inserito nel sistema regionale di raccolta e limitazioni",
      "Mosaico di faggete, castagneti e querceti",
    ],
    elevationRangeM: [300, 1300],
    evidenceSources: [
      {
        label: "Regione Toscana — raccolta funghi",
        url: "https://www.regione.toscana.it/it/-/raccolta-funghi-ecco-le-disposizioni",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "pratomagno",
    name: "Pratomagno e Casentino orientale",
    region: "Toscana",
    center: [43.65, 11.65],
    habitat: ["Faggeta", "Castagneto", "Querceto", "Prati montani"],
    moisture: 76,
    temperatureFit: 80,
    seasonFit: 81,
    verifiedSignals: 64,
    delayedVisitors: 6,
    lastUpdatedLabel: "raccolta regionale verificata, habitat aggregati",
    expectedTaxa: ["boletus-edulis", "russula-cyanoxantha", "craterellus-cornucopioides"],
    reasons: [
      "Area forestale contigua al Casentino, con forte presenza di faggete e castagneti",
      "Raccolta soggetta alla disciplina regionale toscana",
    ],
    elevationRangeM: [350, 1590],
    evidenceSources: [
      {
        label: "Regione Toscana — raccolta funghi",
        url: "https://www.regione.toscana.it/it/-/raccolta-funghi-ecco-le-disposizioni",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "terminillo-monti-reatini",
    name: "Terminillo e Monti Reatini",
    region: "Lazio",
    center: [42.47, 12.99],
    habitat: ["Faggeta", "Querceto", "Prati montani", "Boschi appenninici"],
    moisture: 69,
    temperatureFit: 77,
    seasonFit: 77,
    verifiedSignals: 58,
    delayedVisitors: 6,
    lastUpdatedLabel: "habitat appenninici verificati, segnale territoriale prudenziale",
    expectedTaxa: ["boletus-edulis", "marasmius-oreades", "russula-cyanoxantha"],
    reasons: [
      "Macroarea montana distinta dai Simbruini per quota e fenologia",
      "Peso di evidenza mantenuto prudenziale in attesa di fonti micologiche territoriali più specifiche",
    ],
    elevationRangeM: [600, 2200],
  },
  {
    id: "matese-nazionale",
    name: "Matese centrale",
    region: "Campania",
    center: [41.39, 14.38],
    habitat: ["Faggeta", "Querceto", "Prati montani", "Boschi appenninici"],
    moisture: 75,
    temperatureFit: 79,
    seasonFit: 79,
    verifiedSignals: 72,
    delayedVisitors: 7,
    lastUpdatedLabel: "raccolta funghi pubblicamente documentata",
    expectedTaxa: ["boletus-edulis", "marasmius-oreades", "agaricus-campestris-group"],
    reasons: [
      "La documentazione pubblica sul nuovo Parco nazionale conferma la continuità della raccolta di funghi secondo le norme vigenti",
      "La Regione Campania documenta inoltre il Calocybe gambosa tradizionale nelle aree montane del Matese",
    ],
    elevationRangeM: [500, 1900],
    evidenceSources: [
      {
        label: "Parks.it — raccolta funghi nel Parco nazionale del Matese",
        url: "https://www.parks.it/news/dettaglio.php?id=82286",
        kind: "official-park",
      },
      {
        label: "Regione Campania — Virni (Calocybe gambosa) del Matese",
        url: "https://agricoltura.regione.campania.it/Tipici/tradizionali/virni.html",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "irpinia-terminio-partenio",
    name: "Irpinia, Terminio-Cervialto e Partenio",
    region: "Campania",
    center: [40.94, 14.93],
    habitat: ["Faggeta", "Castagneto", "Querceto", "Boschi montani"],
    moisture: 77,
    temperatureFit: 80,
    seasonFit: 81,
    verifiedSignals: 67,
    delayedVisitors: 8,
    lastUpdatedLabel: "macroarea montana regionale verificata",
    expectedTaxa: ["boletus-edulis", "russula-virescens", "craterellus-cornucopioides"],
    reasons: [
      "La Regione Campania individua Partenio e Terminio-Cervialto come ambiti montani di raccolta di prodotti fungini ipogei",
      "Il segnale viene usato come evidenza di habitat forestale e tradizione micologica, non come fungaia puntuale",
    ],
    elevationRangeM: [400, 1800],
    evidenceSources: [
      {
        label: "Regione Campania — ambiti montani Partenio e Terminio-Cervialto",
        url: "https://funghietartufi.regione.campania.it/zonecomuni.php",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "monti-dauni",
    name: "Monti Dauni e Subappennino",
    region: "Puglia",
    center: [41.32, 15.12],
    habitat: ["Cerreta", "Faggeta", "Querceto", "Prati montani"],
    moisture: 65,
    temperatureFit: 78,
    seasonFit: 74,
    verifiedSignals: 65,
    delayedVisitors: 4,
    lastUpdatedLabel: "habitat forestali regionali verificati",
    expectedTaxa: ["boletus-edulis", "agaricus-campestris-group", "russula-virescens"],
    reasons: [
      "Il PPTR regionale documenta boschi caducifogli, cerrete e nuclei di faggeta nel Subappennino Dauno",
      "Indicatore ecologico di macroarea; nessuna localizzazione di raccolta puntuale",
    ],
    elevationRangeM: [400, 1150],
    evidenceSources: [
      {
        label: "Regione Puglia — PPTR Monti Dauni",
        url: "https://pugliacon.regione.puglia.it/web/sit-puglia-paesaggio/monti-dauni",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "sila-occidentale",
    name: "Sila occidentale e altopiano silano",
    region: "Calabria",
    center: [39.38, 16.35],
    habitat: ["Pino laricio", "Faggeta", "Abetina", "Prati montani"],
    moisture: 78,
    temperatureFit: 79,
    seasonFit: 82,
    verifiedSignals: 94,
    delayedVisitors: 8,
    lastUpdatedLabel: "presenza fungina ufficialmente documentata dal Parco",
    expectedTaxa: ["boletus-edulis", "lactarius-deliciosi", "tricholoma-terreum-group"],
    reasons: [
      "Il Parco della Sila indica Boletus edulis tra i funghi più diffusi e ricercati",
      "Lactarius deliciosus è documentato come molto diffuso nelle giovani pinete di laricio e nelle abetine",
    ],
    elevationRangeM: [900, 1900],
    evidenceSources: [
      {
        label: "Parco Nazionale della Sila — Funghi",
        url: "https://parcosila.it/il-parco/la-flora/funghi/",
        kind: "official-park",
      },
    ],
  },
  {
    id: "aspromonte-occidentale",
    name: "Aspromonte occidentale e Gambarie",
    region: "Calabria",
    center: [38.17, 15.84],
    habitat: ["Faggeta", "Abete bianco", "Pino nero", "Castagneto"],
    moisture: 73,
    temperatureFit: 76,
    seasonFit: 77,
    verifiedSignals: 72,
    delayedVisitors: 6,
    lastUpdatedLabel: "raccolta regolamentata e habitat ufficiali verificati",
    expectedTaxa: ["boletus-edulis", "lactarius-deliciosi", "russula-cyanoxantha"],
    reasons: [
      "Il Parco dispone di regolamento specifico per la raccolta dei funghi epigei",
      "Il Parco documenta vasti boschi di faggio, abete bianco, pino nero e castagno",
    ],
    elevationRangeM: [700, 1950],
    evidenceSources: [
      {
        label: "Parks.it — regolamento raccolta funghi Aspromonte",
        url: "https://www.parks.it/dbdoc/dettaglio.php?id=198",
        kind: "official-park",
      },
      {
        label: "Parco Nazionale dell'Aspromonte — habitat forestali",
        url: "https://www.parks.it/parco.nazionale.aspromonte/index.html",
        kind: "official-park",
      },
    ],
  },
  {
    id: "sette-fratelli-sarrabus",
    name: "Sette Fratelli e Sarrabus",
    region: "Sardegna",
    center: [39.30, 9.39],
    habitat: ["Lecceta", "Sughereta", "Macchia mediterranea", "Boschi demaniali"],
    moisture: 57,
    temperatureFit: 83,
    seasonFit: 70,
    verifiedSignals: 60,
    delayedVisitors: 4,
    lastUpdatedLabel: "foresta demaniale regionale verificata",
    expectedTaxa: ["hygrophorus-russula", "amanita-vaginatae", "agaricus-campestris-group"],
    reasons: [
      "La foresta demaniale di Sette Fratelli è documentata da Forestas",
      "Profilo mediterraneo distinto dalle macroaree montane del Gennargentu",
    ],
    elevationRangeM: [200, 1000],
    evidenceSources: [
      {
        label: "SardegnaForeste — Foresta Sette Fratelli",
        url: "https://www.sardegnaforeste.it/foresta/settefratelli-sinnai",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "goceano-marghine",
    name: "Goceano e Marghine",
    region: "Sardegna",
    center: [40.45, 8.88],
    habitat: ["Querceto", "Sughereta", "Castagneto", "Boschi montani"],
    moisture: 62,
    temperatureFit: 80,
    seasonFit: 72,
    verifiedSignals: 58,
    delayedVisitors: 4,
    lastUpdatedLabel: "macroarea forestale regionale verificata",
    expectedTaxa: ["russula-virescens", "amanita-vaginatae", "boletus-edulis"],
    reasons: [
      "La pianificazione regionale individua Marghine-Goceano come grande macroarea naturale",
      "Segnale ecologico mantenuto prudenziale in assenza di dati pubblici di produttività fungina",
    ],
    elevationRangeM: [300, 1250],
    evidenceSources: [
      {
        label: "Regione Sardegna — aree del Piano dei Parchi",
        url: "https://www.regione.sardegna.it/documenti/1_18_20050214120002.pdf",
        kind: "regional-authority",
      },
    ],
  },
  {
    id: "monti-sicani",
    name: "Monti Sicani e Bosco della Ficuzza",
    region: "Sicilia",
    center: [37.75, 13.42],
    habitat: ["Querceto", "Lecceta", "Castagneto", "Praterie montane"],
    moisture: 58,
    temperatureFit: 80,
    seasonFit: 72,
    verifiedSignals: 61,
    delayedVisitors: 3,
    lastUpdatedLabel: "habitat forestali regionali verificati",
    expectedTaxa: ["boletus-edulis", "russula-virescens", "agaricus-campestris-group"],
    reasons: [
      "La Regione Siciliana documenta quercete miste, leccete, roverelleti e praterie montane nel sistema dei Monti Sicani",
      "La macroarea include boschi Natura 2000 come Ficuzza e Genuardo; nessun punto di raccolta è pubblicato",
    ],
    elevationRangeM: [400, 1200],
    evidenceSources: [
      {
        label: "Regione Siciliana — Rete Natura 2000 Monti Sicani e Bosco della Ficuzza",
        url: "https://orbs.regione.sicilia.it/aree-protette/rete-natura2000.html",
        kind: "regional-authority",
      },
      {
        label: "Regione Siciliana — Monte Genuardo e Santa Maria del Bosco",
        url: "https://orbs.regione.sicilia.it/aree-protette/riserve-naturali-siciliane/176-riserva-naturale-monte-genuardo-e-santa-maria-del-bosco.html",
        kind: "regional-authority",
      },
    ],
  }
];

export const nationalAreas: Area[] = seeds.map((seed, index) => {
  const [id, name, region, latitude, longitude, habitat, expectedTaxa] = seed;
  return {
    id,
    name,
    region,
    center: [latitude, longitude],
    habitat,
    moisture: 62 + ((index * 7) % 25),
    temperatureFit: 66 + ((index * 5) % 23),
    seasonFit: 60 + ((index * 9) % 29),
    verifiedSignals: 35 + ((index * 4) % 31),
    delayedVisitors: (index * 3) % 17,
    lastUpdatedLabel: "dati territoriali aggregati e ritardati",
    expectedTaxa,
    reasons: [
      `Mosaico ambientale: ${habitat.slice(0, 3).join(", ")}`,
      "Valutazione su area vasta, non su punti di raccolta",
    ],
  };
}).concat(verifiedAreaAdditions);
