import test from "node:test";
import assert from "node:assert/strict";
import {approvedOfflineImage,buildOfflinePackage,parseOfflinePackage,readFavoriteIds} from "./offline.ts";
import type {AtlasTaxon} from "./domain.ts";
const taxon:AtlasTaxon={id:"minimum-test",commonName:"Test",scientificName:"Test species",acceptedName:"Test species",sourceName:"Test",rank:"species",aliases:[],regionalNames:[],edibility:"non-valutato",safetyNote:"Identificazione da verificare.",authorship:null,kingdom:"Fungi",division:"Basidiomycota",className:"Agaricomycetes",order:"Agaricales",family:null,parentScientificName:"Test",diagnosticCharacters:[],odor:null,ecology:[],mediaStatus:"preparing",sources:[{title:"Fonte ufficiale",page:1,kind:"obiettivi-minimi"}],objectiveLevels:[],externalIds:{speciesFungorum:null,indexFungorum:null,mycoBank:null}};
test("offline image allowlist excludes APIs, remote URLs, query strings and traversal",()=>{assert.equal(approvedOfflineImage("/schede/s1/test.webp"),"/schede/s1/test.webp");for(const value of ["/api/media?id=1","https://example.com/test.webp","/schede/../private.webp","/schede/x.webp?token=secret","//evil/schede/x.webp"])assert.equal(approvedOfflineImage(value),null);});
test("public snapshot preserves source, safety and identity while dropping private fields",()=>{const input={...taxon,owner:"private",latitude:42,longitude:11,observations:[{note:"private"}]} as AtlasTaxon;const pack=buildOfflinePackage([input],new Date("2026-10-02T00:00:00Z"));assert.equal(pack.cards.length,1);assert.equal(pack.cards[0].id,taxon.id);assert.equal(pack.cards[0].safety,taxon.safetyNote);assert.deepEqual(pack.cards[0].sources,taxon.sources);const raw=JSON.stringify(pack);for(const secret of ["owner","latitude","longitude","observations"])assert.equal(raw.includes(secret),false);assert.equal(parseOfflinePackage(raw)?.version,pack.version);});
test("package revision changes with safety content but not download timestamp",()=>{const one=buildOfflinePackage([taxon],new Date("2026-10-02"));const two=buildOfflinePackage([taxon],new Date("2026-10-03"));assert.equal(one.version,two.version);assert.notEqual(one.version,buildOfflinePackage([{...taxon,safetyNote:"Nuova nota"}]).version);});
test("corrupt saved content and invalid favorites fail safely",()=>{assert.equal(parseOfflinePackage("{invalid"),null);assert.equal(parseOfflinePackage('{"schema":2,"cards":[]}'),null);assert.equal(parseOfflinePackage('{"schema":1,"version":"v","savedAt":"2026-10-02","cachedImages":[],"cards":[null]}'),null);assert.deepEqual(readFavoriteIds('["one","one",42,"two"]'),["one","two"]);assert.deepEqual(readFavoriteIds('{"owner":"private"}'),[]);});
