import type { Area, Taxon } from "./domain";

export const betaTaxa: Taxon[] = [
  {
    id: "boletus-edulis",
    commonName: "Porcino",
    scientificName: "Boletus edulis s.l.",
    rank: "group",
    aliases: [],
    regionalNames: [{ name: "Brisa", regions: ["Trentino-Alto Adige", "Veneto"] }],
    edibility: "commestibile",
    safetyNote: "La conferma della specie richiede l'esame completo dell'esemplare.",
    hosts: ["Faggio", "Castagno", "Abete rosso", "Abete bianco", "Quercia"],
    recognitionLevel: "approfondito",
  },
  {
    id: "russula-cyanoxantha",
    commonName: "Colombina maggiore",
    scientificName: "Russula cyanoxantha",
    rank: "species",
    aliases: [],
    regionalNames: [{ name: "Colombina", regions: ["Emilia-Romagna", "Toscana"] }],
    edibility: "commestibile",
    safetyNote: "Non applicare la prova dell'assaggio senza adeguata competenza.",
    hosts: ["Faggio", "Quercia", "Castagno"],
    recognitionLevel: "auspicabile",
  },
  {
    id: "russula-vesca",
    commonName: "Colombina rosa",
    scientificName: "Russula vesca",
    rank: "species",
    aliases: [],
    regionalNames: [],
    edibility: "commestibile",
    safetyNote: "Identificazione da confermare considerando lamelle, carne e reazioni.",
    hosts: ["Faggio", "Quercia"],
    recognitionLevel: "auspicabile",
  },
  {
    id: "russula-aurea",
    commonName: "Colombina dorata",
    scientificName: "Russula aurea",
    rank: "species",
    aliases: ["Russula aurata"],
    regionalNames: [],
    edibility: "commestibile",
    safetyNote: "La fotografia da sola può non mostrare tutti i caratteri utili.",
    hosts: ["Faggio", "Quercia"],
    recognitionLevel: "auspicabile",
  },
  {
    id: "russula-virescens",
    commonName: "Colombina verde",
    scientificName: "Russula virescens",
    rank: "species",
    aliases: [],
    regionalNames: [{ name: "Verdone", regions: ["Toscana", "Umbria", "Lazio"] }],
    edibility: "commestibile",
    safetyNote: "Attenzione alle possibili confusioni con funghi verdi non appartenenti a Russula.",
    hosts: ["Quercia", "Castagno"],
    recognitionLevel: "auspicabile",
  },
  {
    id: "marasmius-oreades",
    commonName: "Gambesecche",
    scientificName: "Marasmius oreades",
    rank: "species",
    aliases: [],
    regionalNames: [{ name: "Gambe secche", regions: ["Italia settentrionale"] }],
    edibility: "commestibile",
    safetyNote: "Escludere piccoli funghi di prato tossici con caratteri simili.",
    hosts: ["Prati e pascoli"],
    recognitionLevel: "minimo",
  },
  {
    id: "amanita-vaginatae",
    commonName: "Amanite senza anello",
    scientificName: "Amanita sect. Vaginatae",
    rank: "section",
    aliases: [],
    regionalNames: [{ name: "Pettinelle", regions: ["Italia centrale"] }],
    edibility: "commestibile-dopo-trattamento",
    safetyNote: "Gruppo delicato: cottura completa e determinazione certa; possibile confusione con Amanita mortali.",
    hosts: ["Faggio", "Quercia", "Betulla", "Conifere"],
    recognitionLevel: "minimo",
  },
  {
    id: "infundibulicybe-gibba",
    commonName: "Imbutino",
    scientificName: "Infundibulicybe gibba",
    rank: "species",
    aliases: ["Clitocybe gibba"],
    regionalNames: [{ name: "Imbutino", regions: ["Toscana", "Emilia-Romagna"] }],
    edibility: "commestibile-dopo-trattamento",
    safetyNote: "Consumabile soltanto dopo completa cottura e corretta identificazione.",
    hosts: ["Boschi di latifoglie e conifere"],
    recognitionLevel: "minimo",
  },
  {
    id: "pleurotus-eryngii",
    commonName: "Cardoncello",
    scientificName: "Pleurotus eryngii s.l.",
    rank: "group",
    aliases: [],
    regionalNames: [{ name: "Cardoncello", regions: ["Puglia", "Basilicata", "Sardegna"] }],
    edibility: "commestibile",
    safetyNote: "Verificare il legame con le ombrellifere ospiti e tutti i caratteri morfologici.",
    hosts: ["Ferula", "Eryngium", "Pascoli mediterranei"],
    recognitionLevel: "approfondito",
  },
  {
    id: "agaricus-campestris-group",
    commonName: "Prataioli",
    scientificName: "Agaricus gr. campestris",
    rank: "group",
    aliases: [],
    regionalNames: [{ name: "Prataiolo", regions: ["Tutta Italia"] }],
    edibility: "commestibile",
    safetyNote: "Escludere accuratamente gli Agaricus della sezione Xanthodermatei.",
    hosts: ["Prati", "Pascoli"],
    recognitionLevel: "approfondito",
  },
  {
    id: "lactarius-deliciosi",
    commonName: "Lattari aranciati",
    scientificName: "Lactarius sect. Deliciosi",
    rank: "section",
    aliases: [],
    regionalNames: [
      { name: "Sanguinelli", regions: ["Liguria", "Toscana"] },
      { name: "Rositi", regions: ["Basilicata", "Calabria"] },
    ],
    edibility: "commestibile",
    safetyNote: "La specie va definita con lattice, viraggio e pianta simbionte.",
    hosts: ["Pino", "Abete rosso"],
    recognitionLevel: "minimo",
  },
  {
    id: "craterellus-cornucopioides",
    commonName: "Trombetta da morto",
    scientificName: "Craterellus cornucopioides",
    rank: "species",
    aliases: [],
    regionalNames: [{ name: "Trombetta dei morti", regions: ["Italia settentrionale e centrale"] }],
    edibility: "commestibile",
    safetyNote: "Raccogliere soltanto esemplari freschi e integri.",
    hosts: ["Faggio", "Quercia", "Castagno"],
    recognitionLevel: "minimo",
  },
  {
    id: "tricholoma-columbetta",
    commonName: "Colombetta",
    scientificName: "Tricholoma columbetta",
    rank: "species",
    aliases: [],
    regionalNames: [],
    edibility: "commestibile",
    safetyNote: "Il genere comprende specie tossiche: verificare tutti i caratteri.",
    hosts: ["Faggio", "Quercia", "Betulla"],
    recognitionLevel: "minimo",
  },
  {
    id: "tricholoma-terreum-group",
    commonName: "Morette",
    scientificName: "Tricholoma gr. terreum",
    rank: "group",
    aliases: [],
    regionalNames: [{ name: "Moretta", regions: ["Toscana", "Emilia-Romagna", "Lazio"] }],
    edibility: "commestibile",
    safetyNote: "Separare le specie vicine tossiche prima di ogni valutazione alimentare.",
    hosts: ["Pino"],
    recognitionLevel: "approfondito",
  },
  {
    id: "coprinus-comatus",
    commonName: "Fungo dell'inchiostro",
    scientificName: "Coprinus comatus",
    rank: "species",
    aliases: [],
    regionalNames: [{ name: "Coprinus", regions: ["Tutta Italia"] }],
    edibility: "commestibile",
    safetyNote: "Utilizzare soltanto esemplari molto giovani, non deliquescenti e correttamente identificati.",
    hosts: ["Prati", "Margini stradali", "Terreni ricchi"],
    recognitionLevel: "minimo",
  },
  {
    id: "ramaria-botrytis",
    commonName: "Manina buona",
    scientificName: "Ramaria botrytis",
    rank: "species",
    aliases: [],
    regionalNames: [{ name: "Ditola", regions: ["Veneto", "Trentino-Alto Adige"] }],
    edibility: "commestibile",
    safetyNote: "Il genere comprende specie tossiche; accettare solo esemplari giovani e determinati con certezza.",
    hosts: ["Faggio", "Quercia"],
    recognitionLevel: "minimo",
  },
  {
    id: "armillaria-mellea-group",
    commonName: "Chiodini",
    scientificName: "Armillaria gr. mellea",
    rank: "group",
    aliases: [],
    regionalNames: [{ name: "Famigliola buona", regions: ["Italia settentrionale"] }],
    edibility: "commestibile-dopo-trattamento",
    safetyNote: "Richiede trattamento e cottura completa; non consumare esemplari vecchi o dopo gelo.",
    hosts: ["Ceppaie e radici di latifoglie"],
    recognitionLevel: "approfondito",
  },
  {
    id: "cyclocybe-cylindracea",
    commonName: "Pioppino",
    scientificName: "Cyclocybe cylindracea",
    rank: "species",
    aliases: ["Agrocybe aegerita"],
    regionalNames: [
      { name: "Piopparello", regions: ["Toscana", "Umbria"] },
      { name: "Fungo del pioppo", regions: ["Emilia-Romagna", "Veneto"] },
    ],
    edibility: "commestibile",
    safetyNote: "Osservare crescita cespitosa, substrato e caratteri del velo.",
    hosts: ["Pioppo", "Salice"],
    recognitionLevel: "minimo",
  },
  {
    id: "leccinum-leccinellum",
    commonName: "Leccini",
    scientificName: "Leccinum / Leccinellum spp.",
    rank: "group",
    aliases: [],
    regionalNames: [{ name: "Porcinelli", regions: ["Italia settentrionale"] }],
    edibility: "commestibile-dopo-trattamento",
    safetyNote: "Determinare il gruppo e cuocere completamente; evitare esemplari deteriorati.",
    hosts: ["Betulla", "Pioppo", "Quercia", "Carpino", "Nocciolo"],
    recognitionLevel: "minimo",
  },
  {
    id: "hygrophorus-russula",
    commonName: "Lardaiolo",
    scientificName: "Hygrophorus russula",
    rank: "species",
    aliases: [],
    regionalNames: [{ name: "Lardaiolo rosso", regions: ["Toscana", "Lazio"] }],
    edibility: "commestibile",
    safetyNote: "Confermare habitat e caratteri delle lamelle ceracee.",
    hosts: ["Quercia"],
    recognitionLevel: "auspicabile",
  },
  {
    id: "hygrophorus-penarius",
    commonName: "Lardaiolo bianco",
    scientificName: "Hygrophorus penarius",
    rank: "species",
    aliases: [],
    regionalNames: [{ name: "Fungo dal profumo di latte bollito", regions: ["Italia centrale"] }],
    edibility: "commestibile",
    safetyNote: "Non confondere con Hygrophorus penarioides: simbionti e caratteri vanno registrati separatamente.",
    hosts: ["Faggio"],
    recognitionLevel: "auspicabile",
  },
  {
    id: "auricularia-auricula-judae",
    commonName: "Orecchio di Giuda",
    scientificName: "Auricularia auricula-judae",
    rank: "species",
    aliases: [],
    regionalNames: [],
    edibility: "commestibile",
    safetyNote: "Valutare freschezza, substrato e consistenza.",
    hosts: ["Sambuco", "Latifoglie"],
    recognitionLevel: "minimo",
  },
  {
    id: "lycoperdaceae",
    commonName: "Vesce",
    scientificName: "Lycoperdaceae s.l.",
    rank: "family",
    aliases: ["Calvatia spp.", "Lycoperdon spp."],
    regionalNames: [{ name: "Peto di lupo", regions: ["Tutta Italia"] }],
    edibility: "commestibile-dopo-trattamento",
    safetyNote: "Aprire sempre l'esemplare: interno completamente bianco e omogeneo, escludendo giovani Amanita.",
    hosts: ["Prati", "Boschi"],
    recognitionLevel: "minimo",
  },
  {
    id: "morchella",
    commonName: "Spugnole",
    scientificName: "Morchella spp.",
    rank: "genus",
    aliases: [],
    regionalNames: [{ name: "Morchelle", regions: ["Tutta Italia"] }],
    edibility: "commestibile-dopo-trattamento",
    safetyNote: "Sempre dopo trattamento e cottura completa; escludere Gyromitra.",
    hosts: ["Frassino", "Olmo", "Pioppo", "Melo", "Aree disturbate"],
    recognitionLevel: "minimo",
  },
  {
    id: "hygrophorus-marzuolus",
    commonName: "Marzuolo o dormiente",
    scientificName: "Hygrophorus marzuolus",
    rank: "species",
    aliases: [],
    regionalNames: [
      { name: "Dormiente", regions: ["Toscana", "Emilia-Romagna"] },
      { name: "Marzuolo", regions: ["Tutta Italia"] },
    ],
    edibility: "commestibile",
    safetyNote: "Specie spesso interrata: verificare lamelle, carne e habitat.",
    hosts: ["Abete bianco", "Faggio"],
    recognitionLevel: "minimo",
  },
  {
    id: "verpa",
    commonName: "Verpe",
    scientificName: "Verpa spp.",
    rank: "genus",
    aliases: [],
    regionalNames: [],
    edibility: "commestibile-dopo-trattamento",
    safetyNote: "Richiede trattamento e cottura completa; distinguere da specie simili.",
    hosts: ["Boschi ripariali", "Pioppo", "Salice"],
    recognitionLevel: "minimo",
  },
  {
    id: "pleurotus-ostreatus",
    commonName: "Gelone o orecchione",
    scientificName: "Pleurotus ostreatus",
    rank: "species",
    aliases: [],
    regionalNames: [
      { name: "Gelone", regions: ["Toscana", "Umbria"] },
      { name: "Orecchione", regions: ["Italia centrale"] },
    ],
    edibility: "commestibile",
    safetyNote: "Verificare crescita su legno e inserzione laterale del gambo.",
    hosts: ["Pioppo", "Salice", "Faggio", "Latifoglie"],
    recognitionLevel: "minimo",
  },
  {
    id: "flammulina-velutipes",
    commonName: "Fungo dell'olmo",
    scientificName: "Flammulina velutipes s.l.",
    rank: "group",
    aliases: [],
    regionalNames: [{ name: "Chiodino invernale", regions: ["Italia settentrionale"] }],
    edibility: "commestibile-dopo-trattamento",
    safetyNote: "Possibile confusione con specie lignicole tossiche; verificare sporata e gambo vellutato.",
    hosts: ["Olmo", "Pioppo", "Salice", "Latifoglie"],
    recognitionLevel: "minimo",
  },
];

export const betaAreas: Area[] = [
  {
    id: "lagorai-pine",
    name: "Lagorai e Piné",
    region: "Trentino-Alto Adige",
    center: [46.16, 11.26],
    habitat: ["Abete rosso", "Abete bianco", "Faggeta", "Prati montani"],
    moisture: 82,
    temperatureFit: 76,
    seasonFit: 71,
    verifiedSignals: 68,
    delayedVisitors: 12,
    lastUpdatedLabel: "dati dimostrativi ritardati",
    expectedTaxa: ["boletus-edulis", "hygrophorus-marzuolus", "amanita-vaginatae"],
    reasons: ["Umidità del suolo favorevole", "Boschi misti con più fasce altitudinali", "Pressione recente media"],
  },
  {
    id: "appennino-modenese",
    name: "Appennino modenese",
    region: "Emilia-Romagna",
    center: [44.28, 10.83],
    habitat: ["Faggeta", "Castagneto", "Abete bianco", "Prati"],
    moisture: 88,
    temperatureFit: 90,
    seasonFit: 86,
    verifiedSignals: 82,
    delayedVisitors: 2,
    lastUpdatedLabel: "dati dimostrativi ritardati",
    expectedTaxa: ["boletus-edulis", "russula-cyanoxantha", "craterellus-cornucopioides"],
    reasons: ["Piogge pregresse compatibili", "Pochi passaggi aggregati", "Faggete e castagneti in buona finestra"],
  },
  {
    id: "foreste-casentinesi",
    name: "Foreste Casentinesi",
    region: "Toscana",
    center: [43.82, 11.8],
    habitat: ["Faggeta", "Abete bianco", "Querceto", "Castagneto"],
    moisture: 79,
    temperatureFit: 83,
    seasonFit: 78,
    verifiedSignals: 75,
    delayedVisitors: 7,
    lastUpdatedLabel: "dati dimostrativi ritardati",
    expectedTaxa: ["boletus-edulis", "hygrophorus-russula", "ramaria-botrytis"],
    reasons: ["Habitat molto diversificati", "Segnali verificati coerenti", "Passaggi aggregati non ancora elevati"],
  },
  {
    id: "monti-cimini",
    name: "Monti Cimini",
    region: "Lazio",
    center: [42.4, 12.17],
    habitat: ["Faggeta", "Castagneto", "Querceto"],
    moisture: 73,
    temperatureFit: 78,
    seasonFit: 75,
    verifiedSignals: 72,
    delayedVisitors: 18,
    lastUpdatedLabel: "dati dimostrativi ritardati",
    expectedTaxa: ["russula-virescens", "hygrophorus-russula", "craterellus-cornucopioides"],
    reasons: ["Castagneti e faggete potenzialmente produttivi", "Buona compatibilità termica", "Pressione aggregata già elevata"],
  },
  {
    id: "lagonegro-pollino",
    name: "Lagonegrese e Pollino",
    region: "Basilicata",
    center: [40.08, 15.89],
    habitat: ["Faggeta", "Querceto", "Pineta", "Pascoli"],
    moisture: 84,
    temperatureFit: 80,
    seasonFit: 82,
    verifiedSignals: 78,
    delayedVisitors: 3,
    lastUpdatedLabel: "dati dimostrativi ritardati",
    expectedTaxa: ["pleurotus-eryngii", "lactarius-deliciosi", "boletus-edulis"],
    reasons: ["Pascoli e boschi complementari", "Pochi passaggi aggregati", "Segnali compatibili in più habitat"],
  },
  {
    id: "sila-grande",
    name: "Sila Grande",
    region: "Calabria",
    center: [39.36, 16.51],
    habitat: ["Pino laricio", "Faggeta", "Prati montani"],
    moisture: 76,
    temperatureFit: 81,
    seasonFit: 83,
    verifiedSignals: 70,
    delayedVisitors: 5,
    lastUpdatedLabel: "dati dimostrativi ritardati",
    expectedTaxa: ["lactarius-deliciosi", "tricholoma-terreum-group", "boletus-edulis"],
    reasons: ["Pinete adatte ai lattari aranciati", "Finestra termica coerente", "Passaggi aggregati ancora moderati"],
  },
  {
    id: "madonie",
    name: "Madonie",
    region: "Sicilia",
    center: [37.89, 14.02],
    habitat: ["Querceto", "Faggeta mediterranea", "Pascoli"],
    moisture: 58,
    temperatureFit: 72,
    seasonFit: 61,
    verifiedSignals: 54,
    delayedVisitors: 1,
    lastUpdatedLabel: "dati dimostrativi ritardati",
    expectedTaxa: ["pleurotus-eryngii", "agaricus-campestris-group", "marasmius-oreades"],
    reasons: ["Pressione aggregata molto bassa", "Pascoli interessanti", "Umidità ancora discontinua"],
  },
  {
    id: "gennargentu",
    name: "Gennargentu",
    region: "Sardegna",
    center: [40.02, 9.31],
    habitat: ["Querceto", "Castagneto", "Macchia", "Pascoli"],
    moisture: 65,
    temperatureFit: 75,
    seasonFit: 68,
    verifiedSignals: 63,
    delayedVisitors: 0,
    lastUpdatedLabel: "dati dimostrativi ritardati",
    expectedTaxa: ["pleurotus-eryngii", "russula-virescens", "agaricus-campestris-group"],
    reasons: ["Nessun passaggio aggregato pubblicato", "Mosaico di querceti e pascoli", "Condizioni ancora variabili"],
  },
];
