"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Proposal={id:string;fieldId:string;status:string;criticality:string;fieldPath:string;proposedValueJson:string;sourceCitation:string;rationale:string;createdAt:string;reviewNotes:string|null};
const labels:Record<string,string>={submitted:"In attesa di revisione",inReview:"Prima revisione eseguita",changesRequested:"Correzioni richieste",approved:"Approvata: integrazione pubblica in attesa",published:"Pubblicata",rejected:"Respinta"};
function value(raw:string){try{const row=JSON.parse(raw) as Record<string,unknown>;return [row.scientificName,row.rank,row.value].filter(item=>typeof item==="string").join(" · ");}catch{return "Valore non leggibile";}}
export function ProposalHistory(){
 const[rows,setRows]=useState<Proposal[]>([]),[status,setStatus]=useState("loading"),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch("/api/catalog/proposals",{signal:controller.signal,cache:"no-store"}).then(async response=>{const data=await response.json() as {proposals?:Proposal[]};if(!response.ok||!Array.isArray(data.proposals))throw Error("unavailable");if(!controller.signal.aborted){setRows(data.proposals);setStatus("ready");}}).catch(()=>{if(!controller.signal.aborted){setRows([]);setStatus("error");}});return()=>controller.abort();},[attempt]);
 return <main className="mx-auto max-w-4xl p-4 sm:p-8"><Link href="/" className="inline-flex min-h-11 items-center font-bold text-green-900">← Catalogo e mappa</Link><h1 className="text-3xl font-black">Le mie proposte</h1><p className="mt-3">Segui l’esito dei contributi e i riscontri dei revisori. Una proposta inviata non modifica subito il catalogo pubblico.</p><Link href="/catalog/proposals/new" className="my-5 inline-flex min-h-11 items-center rounded-xl bg-green-900 px-4 font-bold text-white">Nuova proposta</Link>{status==="loading"&&<p role="status">Caricamento…</p>}{status==="error"&&<div role="alert"><p>Storico non disponibile.</p><button className="my-3 min-h-11 rounded-xl border px-4" onClick={()=>{setStatus("loading");setAttempt(count=>count+1);}}>Riprova</button></div>}{status==="ready"&&!rows.length&&<p>Non hai ancora inviato proposte.</p>}<div className="space-y-4">{rows.map(row=><article key={row.fieldId} className="min-w-0 break-words rounded-2xl border p-4"><p className="font-bold">{labels[row.status]??row.status}</p><h2 className="mt-2 text-lg font-bold">{row.fieldPath}</h2><p className="mt-2 whitespace-pre-wrap">{value(row.proposedValueJson)}</p><p className="mt-2">Fonte: {row.sourceCitation}</p><p className="mt-2">Motivazione: {row.rationale}</p>{row.reviewNotes&&<p className="mt-3 whitespace-pre-wrap rounded-xl bg-green-50 p-3">Riscontro del revisore: {row.reviewNotes}</p>}{row.status==="changesRequested"&&<p className="mt-3">Invia una nuova proposta corretta con fonte e motivazione aggiornate; il contributo originale resta nello storico.</p>}<p className="mt-3 text-xs">{new Date(row.createdAt.replace(" ","T") + (/(?:Z|[+-]\d{2}:?\d{2})$/.test(row.createdAt) ? "" : "Z")).toLocaleString("it-IT")} · {row.criticality==="critical"?"Revisione rafforzata":"Revisione ordinaria"}</p></article>)}</div>{rows.length===200&&<p className="mt-3">Mostrati i 200 campi proposti più recenti.</p>}</main>;
}
