import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {createAdminPhotoClient,validateAdminManifest,mergeAdminOverride,encryptAdminKey,decryptAdminKey} from '../web/public/admin-photo-core.js';
globalThis.crypto??=webcrypto;
const token='github_pat_'+'x'.repeat(40),hash='a'.repeat(64),date='2026-10-07T12:00:00.000Z';
const row={taxonId:'amanita-caesarea',scientificName:'Amanita caesarea',view:'lateral',src:'images/reference/admin-'+hash+'.jpg',sha256:hash,width:800,height:600,byteLength:10000,subjectTaxon:'Amanita caesarea',attribution:'Gianpaolo Franceschini',source:{kind:'user-provided'},rights:{license:'rights-reserved',publicationScope:'fungo-italia-authorized',authorization:{method:'uploader-declaration',recordedAt:date}},editedBy:'gianpaolobol',updatedAt:date};
const response=(value,status=200)=>({ok:status>=200&&status<300,status,json:async()=>value});
test('single-view replacement preserves other taxa and views',()=>{const top={...row,view:'top'},other={...row,taxonId:'other'};const next=mergeAdminOverride({version:1,images:[row,top,other]},{...row,attribution:'Nuovo autore'});assert.equal(next.images.length,3);assert.equal(next.images.find(x=>x.view==='top'),top);assert.equal(next.images.find(x=>x.taxonId==='other'),other);assert.equal(next.images.find(x=>x.taxonId===row.taxonId&&x.view==='lateral').attribution,'Nuovo autore');});
test('manifest rejects duplicate slots, traversal and invented verification',()=>{assert.throws(()=>validateAdminManifest({version:1,images:[row,row]}));assert.throws(()=>validateAdminManifest({version:1,images:[{...row,src:'../secret'}]}));assert.throws(()=>validateAdminManifest({version:1,images:[{...row,rights:{...row.rights,license:'verified'}}]}));});
test('owner identity and repository push permissions are required',async()=>{let calls=0;const client=createAdminPhotoClient(token,{fetcher:async()=>{calls++;return response({login:'someone-else'});}});await assert.rejects(client.authenticate(),/proprietario/);assert.equal(calls,1);await assert.rejects(client.snapshot(),/Accedi/);const reader=createAdminPhotoClient(token,{fetcher:async url=>response(url.endsWith('/user')?{login:'gianpaolobol'}:{full_name:'gianpaolobol/fungo-italia',default_branch:'main',permissions:{push:false}})});await assert.rejects(reader.authenticate(),/scrittura/);});
test('requests never forward credentials through redirects and logout disables all requests',async()=>{const calls=[];const client=createAdminPhotoClient(token,{fetcher:async(url,options)=>{calls.push({url,options});if(url.endsWith('/git/blobs'))return response({sha:'a'.repeat(40)});return response(url.endsWith('/user')?{login:'gianpaolobol'}:{full_name:'gianpaolobol/fungo-italia',default_branch:'main',permissions:{push:true}});}});await client.authenticate();assert.equal(calls.length,3);for(const call of calls){assert.equal(call.options.redirect,'error');assert.equal(call.options.credentials,'omit');assert.equal(call.options.cache,'no-store');assert.match(call.url,/^https:\/\/api.github.com\/(?:user|repos\/gianpaolobol\/fungo-italia(?:\/git\/blobs)?)$/);}client.dispose();await assert.rejects(client.authenticate(),/annullata|terminata/);assert.equal(calls.length,3);});
test('corrupt existing manifest fails closed',async()=>{const client=createAdminPhotoClient(token,{fetcher:async url=>{if(url.endsWith('/user'))return response({login:'gianpaolobol'});if(url.endsWith('fungo-italia'))return response({full_name:'gianpaolobol/fungo-italia',default_branch:'main',permissions:{push:true}});if(url.endsWith('/git/blobs'))return response({sha:'a'.repeat(40)});if(url.includes('/git/ref/'))return response({object:{sha:'a'.repeat(40)}});if(url.includes('/git/commits/'))return response({tree:{sha:'b'.repeat(40)}});return response({encoding:'base64',size:10,content:btoa('broken')});}});await client.authenticate();await assert.rejects(client.snapshot(),/corrotto/);});
test('cancelled operation makes no request',async()=>{let calls=0;const client=createAdminPhotoClient(token,{fetcher:async()=>{calls++;return response({});}});const controller=new AbortController();controller.abort();await assert.rejects(client.authenticate({signal:controller.signal}),{name:'AbortError'});assert.equal(calls,0);});
test('encrypted device vault roundtrips and rejects wrong passwords and tampering',async()=>{const password='una-password-lunga';const vault=await encryptAdminKey(token,password);assert.equal(await decryptAdminKey(vault,password),token);assert.equal(JSON.stringify(vault).includes(token),false);await assert.rejects(decryptAdminKey(vault,'password-errata'),/Password errata/);await assert.rejects(decryptAdminKey({...vault,ciphertext:vault.ciphertext.slice(0,-4)+'AAAA'},password),/Password errata/);await assert.rejects(encryptAdminKey(token,'short'),/12/);});
test('owner token with read-only Contents cannot unlock edit mode',async()=>{
 const client=createAdminPhotoClient(token,{fetcher:async url=>url.endsWith('/user')?response({login:'gianpaolobol'}):url.endsWith('/git/blobs')?response({},403):response({full_name:'gianpaolobol/fungo-italia',default_branch:'main',permissions:{push:true}})});
 await assert.rejects(client.authenticate(),error=>error.status===403);
 await assert.rejects(client.snapshot(),/Accedi/);
});
test('all canonical teaching titles fit the administrator manifest schema',async()=>{
 const {readFile}=await import('node:fs/promises'),groups=JSON.parse(await readFile(new URL('../src/data/groups.json',import.meta.url),'utf8'));
 for(const group of groups)assert.doesNotThrow(()=>validateAdminManifest({version:1,images:[{...row,taxonId:group.id,scientificName:group.scientificName}]}));
});
