import {questionPhotos} from '../web/public/exam-ui.js';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {buildExamBank,selectCases,gradeAnswer,normalizeName,restoreSession} from '../web/public/exam-core.js';
const taxon={id:'a',rank:'species',scientificName:'Amanita phalloides',aliases:['Tignosa verdognola','Agaricus phalloides'],currentAcceptedNames:['Amanita phalloides'],characters:['a','b','c'],differentiatingCharacter:'volva',sources:[{fields:['edibility'],url:'https://example.org/guide'},{fields:['syndrome'],url:'https://example.org/tox'}],studyProfile:{edibility:{category:'deadly',precautions:[],syndrome:{label:'Falloidea',latency:'Lunga',severity:'Danno epatico'}}},referenceImages:[{subjectTaxon:'Amanita phalloides',src:'images/a.jpg',view:'top',credit:'credit'},{subjectTaxon:'Amanita virosa',src:'images/b.jpg',view:'top'}]};
const bank=buildExamBank([taxon]);
assert.equal(bank.length,1);assert.equal(bank[0].photos.length,1);
assert.equal(buildExamBank([{...taxon,rank:'speciesGroup'}]).length,0);
assert.equal(buildExamBank([{...taxon,referenceImages:[{src:'images/a.jpg'}]}]).length,0);
assert.equal(buildExamBank([{...taxon,studyProfile:{edibility:{category:'toxic',precautions:[]}}}]).length,0);
assert.equal(buildExamBank([{...taxon,studyProfile:{edibility:{category:'conditional',precautions:[]}}}]).length,0);
assert.equal(normalizeName(' Amanita  PHALLOIDES '),'amanita phalloides');
assert.equal(gradeAnswer(bank[0],{name:'Agaricus phalloides',category:'deadly'}).name,true);
assert.equal(gradeAnswer(bank[0],{name:'Tignosa verdognola',category:'deadly'}).name,false);
assert.equal(gradeAnswer(bank[0],{name:'Amanita phalloid',category:'free'}).danger,true);
assert.equal(gradeAnswer(bank[0],{name:'Amanita phalloides',category:'deadly',detail:'qualsiasi testo'}).detail,null);
const many=Array.from({length:18},(_,i)=>({...bank[0],id:String(i)}));
assert.equal(new Set(selectCases(many,15,()=>0.5).map(c=>c.id)).size,15);
assert.throws(()=>selectCases(bank,15),/15/);
assert.equal(restoreSession('{bad',many),null);
assert.equal(restoreSession(JSON.stringify({version:1,mode:'exam',ids:['absent'],answers:[],index:0}),many),null);
assert.equal(restoreSession(JSON.stringify({version:1,mode:'exam',ids:many.slice(0,15).map(c=>c.id),answers:[],index:0,complete:false}),many)?.ids.length,15);
const catalog=JSON.parse(await readFile(new URL('../src/data/catalog.json',import.meta.url)));
const ids=many.slice(0,15).map(c=>c.id);
assert.equal(restoreSession(JSON.stringify({version:1,mode:'exam',ids,answers:[],index:14,complete:false}),many),null);
assert.equal(restoreSession(JSON.stringify({version:1,mode:'training',ids,answers:[{name:'x',category:'free',detail:'',revealed:'yes'}],index:1,complete:false}),many),null);
assert.equal(restoreSession(JSON.stringify({version:1,mode:'exam',ids,answers:[{name:'x',category:false,detail:''}],index:0,complete:false}),many),null);
const profiles=JSON.parse(await readFile(new URL('../src/data/study-profiles.json',import.meta.url)));
assert.ok(buildExamBank(catalog,profiles).length>=15);
const namedPhoto=questionPhotos(bank[0]);
assert.ok(!namedPhoto.includes('Amanita phalloides'));assert.ok(!namedPhoto.includes('credit'));
console.log('Exam bank, exact photo subjects, scientific synonyms, grading and session guards passed');
