import {mkdir,readFile,writeFile,cp,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),web=path.join(root,'web'),output=path.join(root,'dist-ios');
const readJSON=async name=>JSON.parse(await readFile(path.join(root,'src/data',name+'.json'),'utf8'));
const [catalog,groups,areas]=await Promise.all(['catalog','groups','areas'].map(readJSON));
function assert(condition,message){if(!condition)throw Error(message);}
assert(catalog.length===148&&groups.length===66&&areas.length===71,'Baseline counts changed');
assert(new Set([...catalog,...groups].map(t=>t.id)).size===214,'Duplicate taxon IDs');
assert(new Set(areas.map(a=>a.region)).size===20,'Region count changed');
assert(catalog.every(t=>t.characters.length===3&&t.sources.length>=2&&t.independentReviewStatus==='not-attested'),'Scientific provenance missing');
assert(areas.every(a=>Array.isArray(a.center)&&a.center.length===2&&a.center.every(Number.isFinite)&&Math.abs(a.center[0])<=90&&Math.abs(a.center[1])<=180),'Invalid centroid');
const amiata=areas.find(a=>a.name.includes('Amiata'));
assert(amiata&&amiata.center[0]>42&&amiata.center[0]<44&&amiata.center[1]>10&&amiata.center[1]<13,'Amiata latitude/longitude inverted');
const taxonKeys=['id','scientificName','commonNames','summary','characters','lookalikes','habitat','sources','aliases','rank','currentAcceptedNames','currentGenera','kind','relatedIds','deepMorphologyRequired','authorship','family','diagnosticStatus','diagnosticNote'];
const pick=(object,keys)=>Object.fromEntries(keys.filter(key=>key in object).map(key=>[key,object[key]]));
const bibliography=await readJSON('bibliography');
const data={bibliography,version:1,scientificReview:'pending-independent-review',publishedDatabaseChangesIncluded:false,catalog:catalog.map(t=>pick(t,taxonKeys)),groups:groups.map(t=>pick(t,taxonKeys)),areas:areas.map(a=>pick(a,['id','name','region','center','habitat','evidenceSources']))};
await rm(output,{recursive:true,force:true});await mkdir(output,{recursive:true});await cp(path.join(web,'public'),output,{recursive:true});
await writeFile(path.join(output,'data.json'),JSON.stringify(data));
await cp(path.join(root,'assets/icon.png'),path.join(output,'icon.png'));
const vendor=path.join(output,'vendor');await mkdir(vendor,{recursive:true});
for(const name of ['leaflet.js','leaflet.css','images'])await cp(path.join(web,'node_modules/leaflet/dist',name),path.join(vendor,name),{recursive:true});
await cp(path.join(web,'node_modules/leaflet/LICENSE'),path.join(vendor,'LEAFLET-LICENSE.txt'));
const files=['index.html','app.js','app.css','importa-foto.html','importa-foto.js','importa-foto.css','photo-core.js','data.json','manifest.webmanifest','icon.png','sw.js','vendor/leaflet.js','vendor/leaflet.css'];
const hash=createHash('sha256');for(const file of files)hash.update(await readFile(path.join(output,file)));
const version=hash.digest('hex').slice(0,20),sw=await readFile(path.join(output,'sw.js'),'utf8');
await writeFile(path.join(output,'sw.js'),sw.replace('__BUILD_VERSION__',version));
await writeFile(path.join(output,'build.json'),JSON.stringify({version,sourceCommit:process.env.GITHUB_SHA||null,catalogUnits:148,groupCards:66,macroareas:71,scientificReview:'pending-independent-review'},null,2));
console.log(JSON.stringify({output,version,catalogUnits:148,groupCards:66,macroareas:71}));
